# Generated by Django 6.0.2 on 2026-04-08 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('notification_type', models.CharField(choices=[('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_UPDATED', 'Project Details Updated'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('PROJECT_REMINDER', 'Upcoming Project Reminder'), ('REHEARSAL_SCHEDULED', 'New Rehearsal Scheduled'), ('REHEARSAL_UPDATED', 'Rehearsal Time/Location Changed'), ('REHEARSAL_CANCELLED', 'Rehearsal Cancelled'), ('REHEARSAL_REMINDER', 'Upcoming Rehearsal Reminder'), ('PIECE_CASTING_ASSIGNED', 'Assigned to Piece'), ('PIECE_CASTING_UPDATED', 'Piece Casting Changed'), ('MATERIAL_UPLOADED', 'New Sheet Music or Audio Track'), ('CREW_ASSIGNED', 'Assigned to Crew Role'), ('CONTRACT_ISSUED', 'Contract Ready for Review'), ('ABSENCE_REQUESTED', 'Absence Requested by Artist'), ('ABSENCE_APPROVED', 'Absence Request Approved'), ('ABSENCE_REJECTED', 'Absence Request Rejected'), ('SYSTEM_ALERT', 'System Maintenance or Alert')], db_index=True, help_text='Categorization key for frontend routing and icon selection.', max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('URGENT', 'Urgent')], default='INFO', help_text='Urgency level dictating frontend presentation.', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the recipient has viewed this notification.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp of when the notification was marked as read.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Contextual payload. E.g., {'project_id': 'uuid', 'piece_title': 'Requiem', 'voice_type': 'Soprano 1'}.")),
                ('recipient', models.ForeignKey(help_text='The user receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
