# Generated by Django 6.0.2 on 2026-04-23 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_UPDATED', 'Project Details Updated'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('PROJECT_REMINDER', 'Upcoming Project Reminder'), ('REHEARSAL_SCHEDULED', 'New Rehearsal Scheduled'), ('REHEARSAL_UPDATED', 'Rehearsal Time/Location Changed'), ('REHEARSAL_CANCELLED', 'Rehearsal Cancelled'), ('REHEARSAL_REMINDER', 'Upcoming Rehearsal Reminder'), ('PIECE_CASTING_ASSIGNED', 'Assigned to Piece'), ('PIECE_CASTING_UPDATED', 'Piece Casting Changed'), ('MATERIAL_UPLOADED', 'New Sheet Music or Audio Track'), ('CREW_ASSIGNED', 'Assigned to Crew Role'), ('CONTRACT_ISSUED', 'Contract Ready for Review'), ('ABSENCE_REQUESTED', 'Absence Requested by Artist'), ('ABSENCE_APPROVED', 'Absence Request Approved'), ('ABSENCE_REJECTED', 'Absence Request Rejected'), ('SYSTEM_ALERT', 'System Maintenance or Alert')], help_text='The specific business event category this preference applies to.', max_length=50)),
                ('email_enabled', models.BooleanField(default=True, help_text='Delivery authorization for Email channel.')),
                ('push_enabled', models.BooleanField(default=True, help_text='Delivery authorization for Push channel.')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Delivery authorization for SMS channel.')),
                ('user', models.ForeignKey(help_text='The user defining these preferences.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notifications_preference',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'notification_type'), name='unique_active_user_preference_per_type')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('registration_token', models.TextField(help_text='The FCM or APNs device token provided by the client infrastructure.', unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web Browser'), ('IOS', 'Apple iOS'), ('ANDROID', 'Google Android')], default='WEB', help_text='Hardware/Software platform of the registered device.', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the token is currently valid. Invalidated automatically by delivery failures.')),
                ('user', models.ForeignKey(help_text='The user entity owning this device.', on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Device',
                'verbose_name_plural': 'Push Devices',
                'db_table': 'notifications_push_device',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_897d77_idx')],
            },
        ),
    ]
