# Generated by Django 6.0.2 on 2026-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pushdevice_web_push_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='registration_token',
            field=models.TextField(help_text='The FCM/APNs device token (mobile) or Web Push endpoint URL (web).', unique=True),
        ),
    ]
