# Generated by Django 6.0.4 on 2026-06-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_enabled',
        ),
    ]
