# Generated by Django 6.0.4 on 2026-07-24 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_notificationpreference_sms_enabled'),
        ('roster', '0035_identity_vocative_moves_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject_type', models.CharField(choices=[('PROJECT', 'Project'), ('REHEARSAL', 'Rehearsal'), ('CASTING', 'Piece casting')], help_text='Which kind of thing changed.', max_length=20)),
                ('subject_id', models.CharField(help_text='Identity of the changed thing within its type (rehearsal, piece, project).', max_length=64)),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('CHANGED', 'Changed'), ('REMOVED', 'Removed')], help_text='Lifecycle step this row records.', max_length=10)),
                ('notification_type', models.CharField(choices=[('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_UPDATED', 'Project Details Updated'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('PROJECT_REMINDER', 'Upcoming Project Reminder'), ('REHEARSAL_SCHEDULED', 'New Rehearsal Scheduled'), ('REHEARSAL_UPDATED', 'Rehearsal Time/Location Changed'), ('REHEARSAL_CANCELLED', 'Rehearsal Cancelled'), ('REHEARSAL_REMINDER', 'Upcoming Rehearsal Reminder'), ('PIECE_CASTING_ASSIGNED', 'Assigned to Piece'), ('PIECE_CASTING_UPDATED', 'Piece Casting Changed'), ('MATERIAL_UPLOADED', 'New Sheet Music or Audio Track'), ('CONTRACT_ISSUED', 'Contract Ready for Review'), ('ABSENCE_REQUESTED', 'Absence Requested by Artist'), ('ABSENCE_APPROVED', 'Absence Request Approved'), ('ABSENCE_REJECTED', 'Absence Request Rejected'), ('SYSTEM_ALERT', 'System Maintenance or Alert'), ('PARTICIPATION_RESPONSE', 'Artist Project Response'), ('ATTENDANCE_SUBMITTED', 'Artist Attendance Info'), ('CUSTOM_ADMIN_MESSAGE', 'Direct Message from Management'), ('NOTIFICATION_READ_RECEIPT', 'Message Read by Artist'), ('MESSAGE_RECEIVED', 'New Message in Conversation'), ('CHANNEL_MESSAGE', 'New Message in Project Channel')], help_text='The type the published announcement will carry.', max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('URGENT', 'Urgent')], default='INFO', help_text='Urgency of this row alone; a published announcement takes the loudest that survives collapsing.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='The payload exactly as the emitting service built it, minus the diff (rebuilt at publish).')),
                ('change_field', models.CharField(blank=True, help_text="Stable change key for a field diff (e.g. 'date_time'). Empty on creations and removals.", max_length=50)),
                ('change_old', models.TextField(blank=True, help_text='Language-neutral display value before the change. NULL when unset or when the change is label-only.', null=True)),
                ('change_new', models.TextField(blank=True, help_text='Language-neutral display value after the change.', null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When this row was consumed by a publication. NULL = still pending.', null=True)),
                ('project', models.ForeignKey(help_text='The project whose queue this change belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_announcements', to='roster.project')),
                ('recipient', models.ForeignKey(blank=True, help_text='Who this change is personal to. NULL means a broadcast, whose audience is resolved from the live cast at publish time.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Announcement',
                'verbose_name_plural': 'Pending Announcements',
                'db_table': 'notifications_pending_announcement',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'published_at', 'is_deleted'], name='notificatio_project_e171d0_idx')],
            },
        ),
    ]
