# Generated by Django 6.0.4 on 2026-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_project_briefing_and_participation_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_UPDATED', 'Project Details Updated'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('PROJECT_REMINDER', 'Upcoming Project Reminder'), ('PROJECT_BRIEFING', 'Project Briefing'), ('REHEARSAL_SCHEDULED', 'New Rehearsal Scheduled'), ('REHEARSAL_UPDATED', 'Rehearsal Time/Location Changed'), ('REHEARSAL_CANCELLED', 'Rehearsal Cancelled'), ('REHEARSAL_REMINDER', 'Upcoming Rehearsal Reminder'), ('PIECE_CASTING_ASSIGNED', 'Assigned to Piece'), ('PIECE_CASTING_UPDATED', 'Piece Casting Changed'), ('MATERIAL_UPLOADED', 'New Sheet Music or Audio Track'), ('CONTRACT_ISSUED', 'Contract Ready for Review'), ('ABSENCE_REQUESTED', 'Absence Requested by Artist'), ('ABSENCE_APPROVED', 'Absence Request Approved'), ('ABSENCE_REJECTED', 'Absence Request Rejected'), ('SYSTEM_ALERT', 'System Maintenance or Alert'), ('PARTICIPATION_RESPONSE', 'Artist Project Response'), ('ATTENDANCE_SUBMITTED', 'Artist Attendance Info'), ('ANNOUNCEMENT_PENDING', 'Unannounced Changes Waiting'), ('CUSTOM_ADMIN_MESSAGE', 'Direct Message from Management'), ('NOTIFICATION_READ_RECEIPT', 'Message Read by Artist'), ('MESSAGE_RECEIVED', 'New Message in Conversation'), ('CHANNEL_MESSAGE', 'New Message in Project Channel')], db_index=True, help_text='Categorization key for frontend routing and icon selection.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_UPDATED', 'Project Details Updated'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('PROJECT_REMINDER', 'Upcoming Project Reminder'), ('PROJECT_BRIEFING', 'Project Briefing'), ('REHEARSAL_SCHEDULED', 'New Rehearsal Scheduled'), ('REHEARSAL_UPDATED', 'Rehearsal Time/Location Changed'), ('REHEARSAL_CANCELLED', 'Rehearsal Cancelled'), ('REHEARSAL_REMINDER', 'Upcoming Rehearsal Reminder'), ('PIECE_CASTING_ASSIGNED', 'Assigned to Piece'), ('PIECE_CASTING_UPDATED', 'Piece Casting Changed'), ('MATERIAL_UPLOADED', 'New Sheet Music or Audio Track'), ('CONTRACT_ISSUED', 'Contract Ready for Review'), ('ABSENCE_REQUESTED', 'Absence Requested by Artist'), ('ABSENCE_APPROVED', 'Absence Request Approved'), ('ABSENCE_REJECTED', 'Absence Request Rejected'), ('SYSTEM_ALERT', 'System Maintenance or Alert'), ('PARTICIPATION_RESPONSE', 'Artist Project Response'), ('ATTENDANCE_SUBMITTED', 'Artist Attendance Info'), ('ANNOUNCEMENT_PENDING', 'Unannounced Changes Waiting'), ('CUSTOM_ADMIN_MESSAGE', 'Direct Message from Management'), ('NOTIFICATION_READ_RECEIPT', 'Message Read by Artist'), ('MESSAGE_RECEIVED', 'New Message in Conversation'), ('CHANNEL_MESSAGE', 'New Message in Project Channel')], help_text='The specific business event category this preference applies to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='notification_type',
            field=models.CharField(choices=[('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_UPDATED', 'Project Details Updated'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('PROJECT_REMINDER', 'Upcoming Project Reminder'), ('PROJECT_BRIEFING', 'Project Briefing'), ('REHEARSAL_SCHEDULED', 'New Rehearsal Scheduled'), ('REHEARSAL_UPDATED', 'Rehearsal Time/Location Changed'), ('REHEARSAL_CANCELLED', 'Rehearsal Cancelled'), ('REHEARSAL_REMINDER', 'Upcoming Rehearsal Reminder'), ('PIECE_CASTING_ASSIGNED', 'Assigned to Piece'), ('PIECE_CASTING_UPDATED', 'Piece Casting Changed'), ('MATERIAL_UPLOADED', 'New Sheet Music or Audio Track'), ('CONTRACT_ISSUED', 'Contract Ready for Review'), ('ABSENCE_REQUESTED', 'Absence Requested by Artist'), ('ABSENCE_APPROVED', 'Absence Request Approved'), ('ABSENCE_REJECTED', 'Absence Request Rejected'), ('SYSTEM_ALERT', 'System Maintenance or Alert'), ('PARTICIPATION_RESPONSE', 'Artist Project Response'), ('ATTENDANCE_SUBMITTED', 'Artist Attendance Info'), ('ANNOUNCEMENT_PENDING', 'Unannounced Changes Waiting'), ('CUSTOM_ADMIN_MESSAGE', 'Direct Message from Management'), ('NOTIFICATION_READ_RECEIPT', 'Message Read by Artist'), ('MESSAGE_RECEIVED', 'New Message in Conversation'), ('CHANNEL_MESSAGE', 'New Message in Project Channel')], help_text='The type the published announcement will carry.', max_length=50),
        ),
    ]
