# Generated by Django 6.0.4 on 2026-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='device_type',
            field=models.CharField(choices=[('WEB', 'Web Browser')], default='WEB', help_text='Hardware/Software platform of the registered device.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='registration_token',
            field=models.TextField(help_text="The Web Push endpoint URL the browser's push service assigned to this subscription.", unique=True),
        ),
    ]
