# Generated by Django 6.0.4 on 2026-09-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0, help_text='Push service refusals since the last accepted push. The device is deactivated at the limit.'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='last_delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the push service last accepted a push for this device.', null=True),
        ),
    ]
