const fs = require('fs');
const path = require('path');

const PL_DICT = {
  "editor_action_bar.unsaved": "Niezapisane zmiany",
  "contact_filters.no_phone": "Brak telefonu",
  "contact_filters.specialty_other": "Inne",
  "crew.collection.in_view_one": "{{count}} w widoku",
  "crew.collection.in_view_few": "{{count}} w widoku",
  "crew.collection.in_view_many": "{{count}} w widoku",
  "crew.collection.in_view_other": "{{count}} w widoku",
  "crew.filters.active_filters_many": "{{count}} aktywnych filtrów",
  "crew.stats.companies_one": "{{count}} firma",
  "crew.stats.companies_few": "{{count}} firmy",
  "crew.stats.companies_many": "{{count}} firm",
  "crew.stats.companies_other": "{{count}} firm",
  "crew.stats.people_one": "{{count}} współpracownik",
  "crew.stats.people_few": "{{count}} współpracowników",
  "crew.stats.people_many": "{{count}} współpracowników",
  "crew.stats.people_other": "{{count}} współpracowników",
  "crew.stats.specialties_one": "{{count}} specjalizacja w bazie",
  "crew.stats.specialties_few": "{{count}} specjalizacje w bazie",
  "crew.stats.specialties_many": "{{count}} specjalizacji w bazie",
  "crew.stats.specialties_other": "{{count}} specjalizacji w bazie",
  "crew.stats.top_specialty_one": "Najliczniej: {{label}} ({{count}})",
  "crew.stats.top_specialty_few": "Najliczniej: {{label}} ({{count}})",
  "crew.stats.top_specialty_many": "Najliczniej: {{label}} ({{count}})",
  "crew.stats.top_specialty_other": "Najliczniej: {{label}} ({{count}})",
  "dashboard.layout.specialties.INSTRUMENT": "Instrumenty",
  "dashboard.layout.specialties.LIGHT": "Światło",
  "dashboard.layout.specialties.LOGISTICS": "Logistyka",
  "dashboard.layout.specialties.OTHER": "Inne",
  "dashboard.layout.specialties.SOUND": "Dźwięk",
  "dashboard.layout.specialties.VISUALS": "Wizualizacje",
  "dashboard.layout.specialty_descriptions.INSTRUMENT": "Instrumentaliści zewnętrzni i obsługa instrumentów.",
  "dashboard.layout.specialty_descriptions.LIGHT": "Reżyseria świateł, oprawa wizualna sceny.",
  "dashboard.layout.specialty_descriptions.LOGISTICS": "Transport, scena, zabezpieczenie produkcji.",
  "dashboard.layout.specialty_descriptions.OTHER": "Współpracownicy spoza standardowych kategorii.",
  "dashboard.layout.specialty_descriptions.SOUND": "Realizacja dźwięku, miks i nagłośnienie sceniczne.",
  "dashboard.layout.specialty_descriptions.VISUALS": "Multimedia, projekcje, materiał ekranowy.",
  "projects.crew.header.subtitle": "Zatrudnij współpracowników z bazy i przypisz im role na tym koncercie.",
  "projects.crew.header.title": "Ekipa realizacyjna",
  "projects.details.header.subtitle": "Tytuł, harmonogram, dress code i materiały referencyjne projektu.",
  "projects.editor.fab.save": "Zapisz Zmiany",
  "projects.editor.fab.unsaved": "Niezapisane Zmiany",
  "projects.micro_cast.action_bar.description_one": "Przeciągnięto {{count}} zmian. Zapisz, aby zsynchronizować obsadę.",
  "projects.micro_cast.action_bar.description_few": "Przeciągnięto {{count}} zmiany. Zapisz, aby zsynchronizować obsadę.",
  "projects.micro_cast.action_bar.description_many": "Przeciągnięto {{count}} zmian. Zapisz, aby zsynchronizować obsadę.",
  "projects.micro_cast.action_bar.description_other": "Przeciągnięto {{count}} zmian. Zapisz, aby zsynchronizować obsadę.",
  "projects.micro_cast.action_bar.save": "Zapisz casting",
  "projects.micro_cast.artist.pending_label": "Niezapisane",
  "projects.micro_cast.meta.unsaved_one": "Niezapisane: {{count}}",
  "projects.micro_cast.meta.unsaved_few": "Niezapisane: {{count}}",
  "projects.micro_cast.meta.unsaved_many": "Niezapisane: {{count}}",
  "projects.micro_cast.meta.unsaved_other": "Niezapisane: {{count}}",
  "projects.micro_cast.piece_switch.description": "Przełączenie utworu odrzuci wszystkie niezapisane przypisania w tej sekcji. Czy chcesz kontynuować?",
  "projects.micro_cast.piece_switch.discard": "Odrzuć i przełącz",
  "projects.micro_cast.piece_switch.title": "Niezapisane zmiany castingu",
  "projects.micro_cast.toast.save_success": "Casting zapisany",
  "projects.micro_cast.toast.save_success_desc": "Wszystkie zmiany zostały zsynchronizowane.",
  "projects.rehearsals.header.subtitle": "Planuj próby, zarządzaj uczestnictwem sekcji oraz frekwencją.",
  "projects.rehearsals.header.title": "Próby",
  "voice_types.ALT": "Alt",
  "voice_types.BAR": "Baryton",
  "voice_types.BAS": "Bas",
  "voice_types.CT": "Kontratenor",
  "voice_types.MEZ": "Mezzosopran",
  "voice_types.SOP": "Sopran",
  "voice_types.TEN": "Tenor"
};

const EN_DICT = {
  "editor_action_bar.unsaved": "Unsaved changes",
  "contact_filters.no_phone": "No phone",
  "contact_filters.specialty_other": "Other",
  "crew.collection.in_view_one": "{{count}} in view",
  "crew.collection.in_view_other": "{{count}} in view",
  "crew.stats.companies_one": "{{count}} company",
  "crew.stats.companies_other": "{{count}} companies",
  "crew.stats.people_one": "{{count}} collaborator",
  "crew.stats.people_other": "{{count}} collaborators",
  "crew.stats.specialties_one": "{{count}} specialty on file",
  "crew.stats.specialties_other": "{{count}} specialties on file",
  "crew.stats.top_specialty_one": "Top: {{label}} ({{count}})",
  "crew.stats.top_specialty_other": "Top: {{label}} ({{count}})",
  "dashboard.layout.specialties.INSTRUMENT": "Instruments",
  "dashboard.layout.specialties.LIGHT": "Lighting",
  "dashboard.layout.specialties.LOGISTICS": "Logistics",
  "dashboard.layout.specialties.OTHER": "Other",
  "dashboard.layout.specialties.SOUND": "Sound",
  "dashboard.layout.specialties.VISUALS": "Visuals",
  "dashboard.layout.specialty_descriptions.INSTRUMENT": "External instrumentalists and instrument support.",
  "dashboard.layout.specialty_descriptions.LIGHT": "Lighting design and stage visual coverage.",
  "dashboard.layout.specialty_descriptions.LOGISTICS": "Transport, staging, and production safeguarding.",
  "dashboard.layout.specialty_descriptions.OTHER": "Collaborators outside the standard categories.",
  "dashboard.layout.specialty_descriptions.SOUND": "Sound engineering, mixing, and stage amplification.",
  "dashboard.layout.specialty_descriptions.VISUALS": "Multimedia, projections, and screen content.",
  "projects.crew.header.subtitle": "Hire collaborators and assign roles for this production.",
  "projects.crew.header.title": "Technical Crew",
  "projects.details.header.subtitle": "Title, timeline, dress code, and reference materials.",
  "projects.editor.fab.save": "Save Changes",
  "projects.editor.fab.unsaved": "Unsaved Changes",
  "projects.micro_cast.action_bar.description_one": "You dragged {{count}} change. Save to sync cast.",
  "projects.micro_cast.action_bar.description_other": "You dragged {{count}} changes. Save to sync cast.",
  "projects.micro_cast.action_bar.save": "Save casting",
  "projects.micro_cast.artist.pending_label": "Pending",
  "projects.micro_cast.meta.unsaved_one": "Unsaved: {{count}}",
  "projects.micro_cast.meta.unsaved_other": "Unsaved: {{count}}",
  "projects.micro_cast.piece_switch.description": "Switching piece will discard all unsaved assignments. Continue?",
  "projects.micro_cast.piece_switch.discard": "Discard & Switch",
  "projects.micro_cast.piece_switch.title": "Unsaved cast changes",
  "projects.micro_cast.toast.save_success": "Casting saved",
  "projects.micro_cast.toast.save_success_desc": "All changes have been synchronized.",
  "projects.rehearsals.header.subtitle": "Schedule rehearsals, manage section participation and attendance.",
  "projects.rehearsals.header.title": "Rehearsals",
  "voice_types.ALT": "Alto",
  "voice_types.BAR": "Baritone",
  "voice_types.BAS": "Bass",
  "voice_types.CT": "Countertenor",
  "voice_types.MEZ": "Mezzo-soprano",
  "voice_types.SOP": "Soprano",
  "voice_types.TEN": "Tenor"
};

const FR_DICT = {
  "editor_action_bar.unsaved": "Modifications non enregistrées",
  "contact_filters.no_phone": "Pas de téléphone",
  "contact_filters.specialty_other": "Autre",
  "crew.collection.in_view_one": "{{count}} dans la vue",
  "crew.collection.in_view_many": "{{count}} dans la vue",
  "crew.collection.in_view_other": "{{count}} dans la vue",
  "crew.filters.active_filters_many": "{{count}} filtres actifs",
  "crew.stats.companies_one": "{{count}} entreprise",
  "crew.stats.companies_many": "{{count}} entreprises",
  "crew.stats.companies_other": "{{count}} entreprises",
  "crew.stats.people_one": "{{count}} collaborateur",
  "crew.stats.people_many": "{{count}} collaborateurs",
  "crew.stats.people_other": "{{count}} collaborateurs",
  "crew.stats.specialties_one": "{{count}} spécialité enregistrée",
  "crew.stats.specialties_many": "{{count}} spécialités enregistrées",
  "crew.stats.specialties_other": "{{count}} spécialités enregistrées",
  "crew.stats.top_specialty_one": "Plus présent : {{label}} ({{count}})",
  "crew.stats.top_specialty_many": "Plus présent : {{label}} ({{count}})",
  "crew.stats.top_specialty_other": "Plus présent : {{label}} ({{count}})",
  "dashboard.layout.specialties.INSTRUMENT": "Instruments",
  "dashboard.layout.specialties.LIGHT": "Éclairage",
  "dashboard.layout.specialties.LOGISTICS": "Logistique",
  "dashboard.layout.specialties.OTHER": "Autre",
  "dashboard.layout.specialties.SOUND": "Son",
  "dashboard.layout.specialties.VISUALS": "Visuels",
  "dashboard.layout.specialty_descriptions.INSTRUMENT": "Instrumentistes externes et soutien instrumental.",
  "dashboard.layout.specialty_descriptions.LIGHT": "Conception lumière et habillage visuel de la scène.",
  "dashboard.layout.specialty_descriptions.LOGISTICS": "Transport, scène et sécurisation de la production.",
  "dashboard.layout.specialty_descriptions.OTHER": "Collaborateurs hors catégories standard.",
  "dashboard.layout.specialty_descriptions.SOUND": "Ingénierie son, mixage et amplification scénique.",
  "dashboard.layout.specialty_descriptions.VISUALS": "Multimédia, projections et contenus écran.",
  "projects.crew.header.subtitle": "Engagez des collaborateurs et attribuez-leur des rôles pour cette production.",
  "projects.crew.header.title": "Équipe technique",
  "projects.details.header.subtitle": "Titre, chronologie, code vestimentaire et documents de référence.",
  "projects.editor.fab.save": "Enregistrer",
  "projects.editor.fab.unsaved": "Modifications non enregistrées",
  "projects.micro_cast.action_bar.description_one": "Vous avez glissé {{count}} modification. Enregistrez.",
  "projects.micro_cast.action_bar.description_many": "Vous avez glissé {{count}} modifications. Enregistrez.",
  "projects.micro_cast.action_bar.description_other": "Vous avez glissé {{count}} modifications. Enregistrez.",
  "projects.micro_cast.action_bar.save": "Enregistrer casting",
  "projects.micro_cast.artist.pending_label": "En attente",
  "projects.micro_cast.meta.unsaved_one": "Non enregistré: {{count}}",
  "projects.micro_cast.meta.unsaved_many": "Non enregistrés: {{count}}",
  "projects.micro_cast.meta.unsaved_other": "Non enregistrés: {{count}}",
  "projects.micro_cast.piece_switch.description": "Changer de pièce supprimera les affectations non enregistrées. Continuer ?",
  "projects.micro_cast.piece_switch.discard": "Ignorer et changer",
  "projects.micro_cast.piece_switch.title": "Modifications de casting",
  "projects.micro_cast.toast.save_success": "Casting enregistré",
  "projects.micro_cast.toast.save_success_desc": "Toutes les modifications sont synchronisées.",
  "projects.rehearsals.header.subtitle": "Planifiez les répétitions et gérez la présence.",
  "projects.rehearsals.header.title": "Répétitions",
  "voice_types.ALT": "Alto",
  "voice_types.BAR": "Baryton",
  "voice_types.BAS": "Basse",
  "voice_types.CT": "Contre-ténor",
  "voice_types.MEZ": "Mezzo-soprano",
  "voice_types.SOP": "Soprano",
  "voice_types.TEN": "Ténor"
};

function traverse(obj, langDict, currentPath = "") {
  for (let key in obj) {
    const newPath = currentPath ? `${currentPath}.${key}` : key;
    if (typeof obj[key] === 'object' && obj[key] !== null) {
      traverse(obj[key], langDict, newPath);
    } else if (obj[key] === "") {
      if (langDict[newPath]) {
        obj[key] = langDict[newPath];
      }
    }
  }
}

const langs = ['en', 'pl', 'fr'];
const dicts = [EN_DICT, PL_DICT, FR_DICT];

langs.forEach((lang, i) => {
  const filePath = path.join(__dirname, `src/shared/config/locales/${lang}/translation.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  traverse(data, dicts[i]);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
});
console.log("Translations filled!");