"""
# ==========================================
# Django Core Settings
# ==========================================
Django settings for VoctManager Project.
Generated by 'django-admin startproject' using Django 6.0.2.
Author: Krystian Bugalski

This module contains environment-specific configurations.
Sensitive data is loaded via python-dotenv to prevent credential leaks on GitHub.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import sentry_sdk

# Load environment variables from .env file
load_dotenv()

# Base directory path
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY WARNINGS ---
# Keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# Don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

# Allow all hosts during local development. Ensure to set specific domains in production.
ALLOWED_HOSTS = ['*'] if DEBUG else os.environ.get('ALLOWED_HOSTS', '').split(',')

# --- APPLICATION DEFINITION ---
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party packages
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_filters',
    
    # Internal apps
    'core',
    'roster',
    'archive',
]

MIDDLEWARE = [
    # CorsMiddleware MUST be placed as high as possible, especially before any 
    # middleware that can generate responses (like CommonMiddleware).
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# --- DATABASE CONFIGURATION ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'voct_db'),
        'USER': os.environ.get('DB_USER', 'voct_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# --- INTERNATIONALIZATION ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- STATIC & MEDIA FILES ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Directory for user-uploaded files (e.g., PDF scores, audio tracks)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- DJANGO REST FRAMEWORK CONFIGURATION ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Primary authentication for React frontend
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Fallback for browsable API testing in Django Admin
        'rest_framework.authentication.SessionAuthentication', 
    ),
    # Secure API by default: Require authentication for all endpoints
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '300/minute'
    }
}

# --- SWAGGER / OPENAPI SETTINGS ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'VoctManager API',
    'DESCRIPTION': 'Enterprise API for VoctEnsemble a cappella octet.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'jwtAuth': []}],
    'COMPONENT_SPLIT_REQUEST': True,
}

# --- JWT (JSON Web Token) SETTINGS ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- CORS (Cross-Origin Resource Sharing) CONFIGURATION ---
# Dynamically load allowed origins from .env to easily switch between dev and production
cors_env = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173')
CORS_ALLOWED_ORIGINS = cors_env.split(',')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- CELERY & REDIS CONFIGURATION ---
# Redis server address acting as the message broker (task queue)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")

# Database to store task results and statuses (PENDING, SUCCESS, FAILED)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")

# Serialization formats for data passed between Django and Celery
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# --- BUSINESS LOGIC DEFAULTS ---
# Default password for automatically provisioned artist accounts
DEFAULT_ARTIST_PASSWORD = os.environ.get('DEFAULT_ARTIST_PASSWORD', 'secure_password123')

sentry_dsn = os.environ.get('SENTRY_DSN')
if sentry_dsn:
    sentry_sdk.init(
        dsn=sentry_dsn,
        traces_sample_rate=0.2,
        profiles_sample_rate=0.2,
    )

if not DEBUG:
    # Ensure session and CSRF cookies are only sent over secure HTTPS connections
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Enforce HTTP Strict Transport Security (HSTS) for 1 year
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Force redirection from HTTP to HTTPS
    SECURE_SSL_REDIRECT = True