# Generated by Django 6.0.4 on 2026-09-05 02:14

import django.db.models.deletion
import outreach.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertNoticeSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(help_text='One row per address; re-subscribing reuses it rather than duplicating.', max_length=254, unique=True, verbose_name='Email')),
                ('locale', models.CharField(choices=[('pl', 'Polish'), ('en', 'English'), ('fr', 'French')], default='pl', max_length=2, verbose_name='Language')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting confirmation'), ('CONFIRMED', 'Confirmed'), ('UNSUBSCRIBED', 'Unsubscribed')], db_index=True, default='PENDING', max_length=12, verbose_name='Status')),
                ('confirm_token', models.CharField(blank=True, help_text='The secret in the double opt-in link; re-issued on every fresh sign-up.', max_length=64, null=True, unique=True, verbose_name='Confirmation token')),
                ('confirm_sent_at', models.DateTimeField(blank=True, help_text="Start of the token's life, and the floor for the resend cooldown.", null=True, verbose_name='Confirmation requested at')),
                ('unsubscribe_token', models.CharField(default=outreach.models.new_token, editable=False, max_length=64, unique=True, verbose_name='Unsubscribe token')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='The moment the double opt-in closed. This is the consent itself.', null=True, verbose_name='Confirmed at')),
                ('clause_version', models.CharField(help_text='Version of the information clause displayed at sign-up (outreach/consent.py).', max_length=16, verbose_name='Clause version')),
                ('surface', models.CharField(help_text='Where the sign-up was given, e.g. `web:koncerty`.', max_length=64, verbose_name='Surface')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed at')),
            ],
            options={
                'verbose_name': 'Concert notice subscription',
                'verbose_name_plural': 'Concert notice subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='outreach_notice_isdel_idx'), models.Index(fields=['status', 'locale'], name='outreach_notice_status_loc_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoticeConsentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('GRANTED', 'Consent granted'), ('WITHDRAWN', 'Consent withdrawn')], max_length=12, verbose_name='Event')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='At')),
                ('clause_version', models.CharField(max_length=16, verbose_name='Clause version')),
                ('surface', models.CharField(blank=True, max_length=64, verbose_name='Surface')),
                ('locale', models.CharField(choices=[('pl', 'Polish'), ('en', 'English'), ('fr', 'French')], max_length=2, verbose_name='Language')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to='outreach.concertnoticesubscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Notice consent event',
                'verbose_name_plural': 'Notice consent events',
                'ordering': ['-at'],
            },
        ),
    ]
