# Generated by Django 6.0.4 on 2026-09-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertnoticesubscription',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. Used for nothing but the greeting of the notice itself.', max_length=80, verbose_name='First name'),
        ),
    ]
