# Generated by Django 6.0.4 on 2026-10-01 20:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_concertnoticesubscription_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concert', models.CharField(db_index=True, max_length=64, verbose_name='Concert')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full name')),
                ('name_key', models.CharField(editable=False, max_length=255)),
                ('seats', models.PositiveSmallIntegerField(help_text='0 means the guest will not come.', verbose_name='Seats')),
                ('concert_starts_at', models.DateTimeField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Received at')),
            ],
            options={
                'verbose_name': 'Concert reservation',
                'verbose_name_plural': 'Concert reservations',
                'ordering': ['name_key', '-created_at'],
            },
        ),
    ]
