# Wymuszamy HTTPS dla wszystkich
server {
    listen 80;
    server_name voctensemble.com www.voctensemble.com test.voctensemble.com;
    return 301 https://$host$request_uri;
}

# 1. GŁÓWNA DOMENA -> STRONA W BUDOWIE
server {
    listen 443 ssl;
    server_name voctensemble.com www.voctensemble.com;

    ssl_certificate /etc/letsencrypt/live/voctensemble.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/voctensemble.com/privkey.pem;

    location / {
        root /usr/share/nginx/html/maintenance;
        index index.html;
    }
}

# 2. SUBDOMENA TESTOWA -> REACT + DJANGO API
server {
    listen 443 ssl;
    server_name test.voctensemble.com;

    ssl_certificate /etc/letsencrypt/live/voctensemble.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/voctensemble.com/privkey.pem;

    # WYCIĄGNIĘTY ROOT (Teraz Nginx wie, że React i Wideo żyją w folderze 'app')
    root /usr/share/nginx/html/app;

    # React Frontend
    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Obsługa Wideo z Reacta (Teraz dziedziczy poprawnego roota!)
    location ~* \.(mp4|webm|ogg)$ {
        add_header Accept-Ranges bytes;
        add_header Content-Type video/mp4; 
        log_not_found off;
        access_log off;
        try_files $uri =404; # Upewnia się, że zwróci czyste 404, jeśli pliku brak
    }

    # Django API & Admin
    location ~ ^/(api|admin) {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # PLIKI STATYCZNE DJANGO (CSS dla panelu Admina)
    location /static/ {
        # Zamiast proxy, Nginx serwuje to z dysku
        alias /app/static/; 
    }
    
    # PLIKI MEDIA DJANGO (Zdjęcia/Nuty wgrywane przez Admina)
    location /media/ {
        # Zamiast proxy, Nginx serwuje to z dysku
        alias /app/media/; 
    }

    # Obsługa błędów
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
