/**
 * @file foundation.ts
 * @description Who the foundation is, as data: the registered name, the seat, the three registry
 *  numbers, the founding date, the board and its KRS functions, the foundation's own social
 *  profiles, the two accounts and the addresses. The facts an organiser needs to sign a contract
 *  or issue a transfer, in one place.
 *
 *  IT EXISTS BECAUSE A NUMBER IS NOT PROSE. KRS, NIP and REGON are printed on nine surfaces of
 *  this site and were typed out on every one of them; `docs/specs/web-colophon-remediation.md` records
 *  that as a defect waiting for a registry change to expose it. They are also needed OUTSIDE a
 *  page — the press pack's invoicing sheet is generated by a Node script, which cannot read an
 *  `.astro` template — and that is what finally forced a module: a fact two different runtimes
 *  print has nowhere else to live.
 *
 *  NOT ON THE COPY DESK, AND NOT A CANDIDATE FOR IT. A registry number is not a sentence anybody
 *  reviews or translates; it is identical in all three locales and wrong is wrong in each of them.
 *  The rule the desk draws (§6r — can completeness be demanded) puts it on the same side as a
 *  landmark, and one step further: there is not even a per-locale form.
 *
 *  THE SWEEP IS NOT DONE. Seven display surfaces still carry their own copy of these strings
 *  (SiteFooter ×2, FinalSupportSection, AboutPage, ContactPage, KolofonPage, and the policy /
 *  terms YAML, where the number sits inside a sentence and belongs to the desk). Converting them
 *  is mechanical and is deliberately a separate pass; what this module closed is the one
 *  duplicate that contradicted itself — two files each declaring in their header that they were
 *  the only home of the bank details.
 *
 *  PURE BY CONTRACT. Imported by Astro pages AND by `scripts/press-pack.mjs` under plain Node,
 *  so it stays free of `?raw`, `astro:*` and anything else only a bundler resolves.
 * @architecture Astro islands 2026
 * @module data/foundation
 */

export interface BankAccount {
  /** The IBAN as a bank's field wants it: no spaces, no country prefix stripped. */
  readonly iban: string;
  /** The same number grouped for a human to read and check against a screen. */
  readonly display: string;
  /** Domestic form (NRB) — what a Polish transfer form asks for. */
  readonly nrb: string;
}

/** A board seat as the KRS register carries it. The words for it are copy, per locale. */
export type BoardFunction = "president" | "vicePresident";

export interface BoardMember {
  /** Stable key shared with /o-nas's role lines and portraits. */
  readonly id: "florent" | "ania" | "krystian";
  readonly name: string;
  readonly function: BoardFunction;
}

export interface SocialProfile {
  readonly network: "facebook" | "instagram";
  /** The canonical profile URL — never a share or redirect link. */
  readonly url: string;
}

export interface Foundation {
  /** As the register carries it — the name that goes on a contract. */
  readonly name: string;
  /** Without the legal form, for a line that already says "Fundacja" beside it. */
  readonly nameShort: string;
  /** The ensemble the foundation runs. A different object from the foundation, on purpose. */
  readonly ensemble: string;
  readonly seat: {
    readonly street: string;
    readonly postalCode: string;
    readonly city: string;
    readonly countryCode: "PL";
  };
  /** The seat as one line, which is how every surface actually prints it. */
  readonly addressLine: string;
  readonly registry: {
    readonly krs: string;
    readonly nip: string;
    readonly regon: string;
  };
  /** ISO date the foundation was established — the line /fundacja draws between the ensemble's
      own record and the foundation's realisations. */
  readonly foundedOn: string;
  /** The management board in the register's order: the president, then the vice-presidents. */
  readonly board: readonly BoardMember[];
  /** The foundation's own profiles, not the ensemble's (`data/social.ts`). Only accounts that
      exist; a surface prints nothing for an empty list. */
  readonly socials: readonly SocialProfile[];
  readonly accounts: {
    readonly pln: BankAccount;
    /** A second account in EUR. It exists for a foreign organiser and for nothing else. */
    readonly eur: BankAccount;
  };
  readonly mail: {
    readonly booking: string;
    readonly general: string;
    readonly patronage: string;
    /** Everything /fundacja asks a reader to write about — the foundation's own domain. */
    readonly foundation: string;
    /** /mecenat only: the address its contact person reads. */
    readonly mecenat: string;
    /** Journalists. The foundation's own domain, as printed on its press releases. */
    readonly press: string;
    readonly director: string;
  };
  readonly site: string;
}

/**
 * The foundation's own identity. Every string here is verifiable in the KRS register or on a bank
 * statement — nothing is derived and nothing is approximate.
 *
 * NO BANK NAME. The repository has never carried one, and the number is what a transfer needs;
 * writing a bank's name from the IBAN prefix would be a guess printed as a fact on a document an
 * organiser pays against.
 */
export const FOUNDATION: Foundation = {
  name: "Fundacja VoctFoundation",
  nameShort: "VoctFoundation",
  ensemble: "VoctEnsemble",
  seat: {
    street: "ul. Św. Filipa 23/3",
    postalCode: "31-150",
    city: "Kraków",
    countryCode: "PL",
  },
  addressLine: "ul. Św. Filipa 23/3, 31-150 Kraków",
  registry: {
    krs: "0001237252",
    nip: "6762718992",
    regon: "544621525",
  },
  foundedOn: "2026-04-15",
  board: [
    { id: "florent", name: "Florent de Bazelaire", function: "president" },
    { id: "ania", name: "Anna Marcisz", function: "vicePresident" },
    { id: "krystian", name: "Krystian Bugalski", function: "vicePresident" },
  ],
  socials: [{ network: "facebook", url: "https://www.facebook.com/profile.php?id=61590395972435" }],
  accounts: {
    pln: {
      iban: "PL26160010131724418410000001",
      display: "PL26 1600 1013 1724 4184 1000 0001",
      nrb: "26160010131724418410000001",
    },
    eur: {
      iban: "PL96160010131724418410000002",
      display: "PL96 1600 1013 1724 4184 1000 0002",
      nrb: "96160010131724418410000002",
    },
  },
  mail: {
    booking: "booking@voctensemble.com",
    general: "kontakt@voctensemble.com",
    patronage: "patronat@voctensemble.com",
    foundation: "fundacja@voctfoundation.com",
    mecenat: "mecenat@voctfoundation.com",
    press: "press@voctfoundation.com",
    director: "florent.de.bazelaire@voctensemble.com",
  },
  site: "https://voctensemble.com",
};

/* NO `registryLine()` HELPER, and the absence is deliberate. One shipped here briefly, justified
   by "so a surface cannot invent its own order" — and had no callers, because the two surfaces
   that print these numbers want different things: /press renders the full set as a definition
   list it builds from its own ordered array, and the closing signature line is a shorter object
   (name, seat, KRS, NIP) rather than the same line abbreviated. A helper written for callers that
   do not exist reads, a year later, as one whose callers were removed. Add it when a second
   surface actually wants the identical string. */
