# finance/urls.py
# ==========================================
# Finance — URL routing (mounted at /api/finance/)
# Standard: Enterprise SaaS 2026
# ==========================================
from django.urls import path

from .views import (
    AnnulContractView,
    AttachmentDetailView,
    AttachmentUploadView,
    BudgetApproveView,
    BudgetCloseView,
    BudgetHistoryView,
    BudgetReopenView,
    ContractBillView,
    ContractHoursView,
    ContractPdfView,
    ContractsZipFileView,
    ContractsZipStatusView,
    CostAllocationsView,
    CostItemDetailView,
    DocumentNotesPdfView,
    ExpenseCollectionView,
    ExpenseDetailView,
    FinanceOverviewView,
    FundingChargeView,
    FundingCollectionView,
    FundingDetailView,
    FundingSourceCollectionView,
    FundingSourceDetailView,
    IssueContractView,
    KosztorysActualCsvView,
    KosztorysCsvView,
    LedgerCsvView,
    LineAllocationsView,
    LineChargeView,
    LineCollectionView,
    LineDetailView,
    LineReorderView,
    OneOffFeeView,
    PayExpensesView,
    PayFeesView,
    ProjectBudgetView,
    ProjectContractsZipView,
    ProjectFeesView,
    ProjectLedgerCsvView,
    ReportPdfView,
    SignContractView,
    UnpayView,
)

app_name = 'finance'

urlpatterns = [
    path('overview/', FinanceOverviewView.as_view(), name='overview'),
    path('export/ledger.csv', LedgerCsvView.as_view(), name='ledger-csv'),
    path(
        'projects/<uuid:project_id>/export/ledger.csv', ProjectLedgerCsvView.as_view(), name='project-ledger-csv',
    ),
    path(
        'projects/<uuid:project_id>/export/kosztorys-plan.csv',
        KosztorysCsvView.as_view(), name='project-kosztorys-plan-csv',
    ),
    path(
        'projects/<uuid:project_id>/export/kosztorys-actual.csv',
        KosztorysActualCsvView.as_view(), name='project-kosztorys-actual-csv',
    ),
    path('projects/<uuid:project_id>/report.pdf', ReportPdfView.as_view(), name='project-report'),
    path(
        'projects/<uuid:project_id>/document-notes.pdf', DocumentNotesPdfView.as_view(), name='project-document-notes',
    ),
    path('projects/<uuid:project_id>/budget/', ProjectBudgetView.as_view(), name='project-budget'),
    path('projects/<uuid:project_id>/budget/approve/', BudgetApproveView.as_view(), name='project-budget-approve'),
    path('projects/<uuid:project_id>/budget/reopen/', BudgetReopenView.as_view(), name='project-budget-reopen'),
    path('projects/<uuid:project_id>/budget/close/', BudgetCloseView.as_view(), name='project-budget-close'),
    path('projects/<uuid:project_id>/history/', BudgetHistoryView.as_view(), name='project-history'),
    path('projects/<uuid:project_id>/lines/', LineCollectionView.as_view(), name='project-lines'),
    path('projects/<uuid:project_id>/lines/reorder/', LineReorderView.as_view(), name='project-lines-reorder'),
    path('projects/<uuid:project_id>/lines/<uuid:pk>/', LineDetailView.as_view(), name='project-line'),
    path('projects/<uuid:project_id>/lines/<uuid:pk>/charge/', LineChargeView.as_view(), name='project-line-charge'),
    path(
        'projects/<uuid:project_id>/lines/<uuid:pk>/allocations/',
        LineAllocationsView.as_view(), name='project-line-allocations',
    ),
    path('projects/<uuid:project_id>/fundings/', FundingCollectionView.as_view(), name='project-fundings'),
    path('projects/<uuid:project_id>/fundings/<uuid:pk>/', FundingDetailView.as_view(), name='project-funding'),
    path(
        'projects/<uuid:project_id>/fundings/<uuid:pk>/charge/',
        FundingChargeView.as_view(), name='project-funding-charge',
    ),
    path('funding-sources/', FundingSourceCollectionView.as_view(), name='funding-sources'),
    path('funding-sources/<uuid:pk>/', FundingSourceDetailView.as_view(), name='funding-source'),
    path('projects/<uuid:project_id>/expenses/', ExpenseCollectionView.as_view(), name='project-expenses'),
    path('projects/<uuid:project_id>/expenses/pay/', PayExpensesView.as_view(), name='project-expenses-pay'),
    path('projects/<uuid:project_id>/expenses/<uuid:pk>/', ExpenseDetailView.as_view(), name='project-expense'),
    path('attachments/', AttachmentUploadView.as_view(), name='attachments'),
    path('attachments/<uuid:pk>/', AttachmentDetailView.as_view(), name='attachment'),
    path('projects/<uuid:project_id>/fees/', ProjectFeesView.as_view(), name='project-fees'),
    path('projects/<uuid:project_id>/fees/one-off/', OneOffFeeView.as_view(), name='project-fees-one-off'),
    path('projects/<uuid:project_id>/fees/pay/', PayFeesView.as_view(), name='project-fees-pay'),
    path('cost-items/<uuid:pk>/', CostItemDetailView.as_view(), name='cost-item-detail'),
    path('cost-items/<uuid:pk>/unpay/', UnpayView.as_view(), name='cost-item-unpay'),
    path('cost-items/<uuid:pk>/allocations/', CostAllocationsView.as_view(), name='cost-item-allocations'),
    path('cost-items/<uuid:pk>/contract/', IssueContractView.as_view(), name='cost-item-contract'),
    path('contracts/<uuid:pk>/sign/', SignContractView.as_view(), name='contract-sign'),
    path('contracts/<uuid:pk>/hours/', ContractHoursView.as_view(), name='contract-hours'),
    path('contracts/<uuid:pk>/annul/', AnnulContractView.as_view(), name='contract-annul'),
    path('contracts/<uuid:pk>/pdf/', ContractPdfView.as_view(), name='contract-pdf'),
    path('contracts/<uuid:pk>/bill.pdf', ContractBillView.as_view(), name='contract-bill'),
    path('projects/<uuid:project_id>/contracts/zip/', ProjectContractsZipView.as_view(), name='project-contracts-zip'),
    path('contracts/zip/<uuid:task_id>/', ContractsZipStatusView.as_view(), name='contracts-zip-status'),
    path('contracts/zip/<uuid:task_id>/file/', ContractsZipFileView.as_view(), name='contracts-zip-file'),
]
