# Generated by Django 6.0.4 on 2026-09-23 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0061_rehearsalplanitem_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('form', models.CharField(choices=[('DZIELO', 'Contract for a specific work'), ('ZLECENIE', 'Contract of mandate'), ('INVOICE', 'Invoice'), ('VOLUNTEER', 'Volunteer'), ('OTHER', 'Other')], max_length=10, verbose_name='Form')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Last number')),
            ],
            options={
                'verbose_name': 'Contract sequence',
                'verbose_name_plural': 'Contract sequences',
                'constraints': [models.UniqueConstraint(fields=('year', 'form'), name='finance_sequence_unique_year_form')],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='PLANNING', max_length=10, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('internal_note', models.TextField(blank=True, verbose_name='Internal note')),
                ('patron_summary', models.TextField(blank=True, verbose_name='Summary for patrons')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Closed by')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='roster.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project budget',
                'verbose_name_plural': 'Project budgets',
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('FEE', 'Fee'), ('EXPENSE', 'Expense')], default='FEE', max_length=8, verbose_name='Kind')),
                ('category', models.CharField(choices=[('PERSONNEL_ARTISTIC', 'Artistic personnel'), ('PERSONNEL_TECHNICAL', 'Technical personnel'), ('VENUE', 'Venue'), ('TRAVEL', 'Travel'), ('ACCOMMODATION', 'Accommodation'), ('CATERING', 'Catering'), ('MATERIALS', 'Materials and rights'), ('EQUIPMENT', 'Equipment'), ('PROMOTION', 'Promotion'), ('RECORDING', 'Recording'), ('ADMINISTRATION', 'Administration'), ('OTHER', 'Other')], max_length=24, verbose_name='Category')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost to the foundation')),
                ('incurred_on', models.DateField(verbose_name='Incurred on')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='Due on')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='Paid on')),
                ('paid_marked_at', models.DateTimeField(blank=True, null=True, verbose_name='Marked paid at')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('payee_name', models.CharField(blank=True, max_length=200, verbose_name='Payee')),
                ('payee_role', models.CharField(blank=True, max_length=150, verbose_name='Payee role')),
                ('form', models.CharField(blank=True, choices=[('DZIELO', 'Contract for a specific work'), ('ZLECENIE', 'Contract of mandate'), ('INVOICE', 'Invoice'), ('VOLUNTEER', 'Volunteer'), ('OTHER', 'Other')], max_length=10, verbose_name='Form')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contract amount')),
                ('employer_contributions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Employer contributions')),
                ('in_kind_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Volunteer hours')),
                ('in_kind_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volunteer hourly valuation')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Document number')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Document date')),
                ('vendor_nip', models.CharField(blank=True, max_length=13, verbose_name='Vendor NIP')),
                ('crew_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='roster.crewassignment', verbose_name='Crew assignment')),
                ('paid_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Marked paid by')),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='roster.participation', verbose_name='Cast seat')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='finance.projectbudget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Cost item',
                'verbose_name_plural': 'Cost items',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Number')),
                ('form', models.CharField(choices=[('DZIELO', 'Contract for a specific work'), ('ZLECENIE', 'Contract of mandate'), ('INVOICE', 'Invoice'), ('VOLUNTEER', 'Volunteer'), ('OTHER', 'Other')], max_length=10, verbose_name='Form')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payee_name', models.CharField(max_length=200, verbose_name='Payee')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued at')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('SIGNED', 'Signed'), ('ANNULLED', 'Annulled')], default='ISSUED', max_length=8, verbose_name='Status')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='Signed on')),
                ('signed_copy_location', models.CharField(blank=True, max_length=300, verbose_name='Signed copy location')),
                ('hours_confirmed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hours confirmed')),
                ('annulled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulled at')),
                ('annul_reason', models.TextField(blank=True, verbose_name='Reason for annulment')),
                ('annulled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Annulled by')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Issued by')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='finance.costitem', verbose_name='Cost item')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('status', 'ANNULLED'), _negated=True)), fields=('cost_item',), name='finance_contract_one_live_per_item', violation_error_message='A cost item has at most one contract that is not annulled.'), models.CheckConstraint(condition=models.Q(('form__in', ('DZIELO', 'ZLECENIE', 'VOLUNTEER'))), name='finance_contract_form_issuable')],
            },
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='At')),
                ('subject_type', models.CharField(max_length=20, verbose_name='Subject type')),
                ('subject_id', models.UUIDField(verbose_name='Subject id')),
                ('action', models.CharField(choices=[('IMPORTED', 'Imported from the roster'), ('CREATED', 'Created'), ('PRICED', 'Priced'), ('FORM_CHANGED', 'Form changed'), ('DETAILS_CHANGED', 'Details changed'), ('PAID', 'Marked paid'), ('UNPAID', 'Payment reverted'), ('REMOVED', 'Removed'), ('CONTRACT_ISSUED', 'Contract issued'), ('CONTRACT_SIGNED', 'Contract signed'), ('CONTRACT_HOURS', 'Hours confirmed'), ('CONTRACT_ANNULLED', 'Contract annulled'), ('BUDGET_APPROVED', 'Budget approved'), ('BUDGET_REOPENED', 'Budget reopened'), ('BUDGET_CLOSED', 'Budget closed'), ('PLAN_CHANGED', 'Plan changed'), ('ALLOCATION_CHANGED', 'Allocation changed')], max_length=20, verbose_name='Action')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='Before')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='After')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.projectbudget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Finance event',
                'verbose_name_plural': 'Finance events',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['budget', '-at'], name='finance_event_budget_at_idx'), models.Index(fields=['subject_type', 'subject_id'], name='finance_event_subject_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='costitem',
            index=models.Index(fields=['budget', 'kind'], name='finance_item_budget_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='costitem',
            index=models.Index(fields=['paid_on'], name='finance_item_paid_on_idx'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('participation__isnull', False), ('crew_assignment__isnull', False), _negated=True), name='finance_item_one_source', violation_error_message='A cost item comes from a cast seat or a crew assignment, not both.'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('participation__isnull', False)), fields=('participation',), name='finance_item_unique_participation'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.UniqueConstraint(condition=models.Q(('crew_assignment__isnull', False), ('is_deleted', False)), fields=('crew_assignment',), name='finance_item_unique_crew_assignment'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_amount', 0), ('form', 'VOLUNTEER')), models.Q(models.Q(('form', 'VOLUNTEER'), _negated=True), models.Q(('contract_amount__isnull', True), ('contract_amount__gt', 0), _connector='OR')), _connector='OR'), name='finance_item_zero_is_volunteer', violation_error_message='An amount of 0 means volunteer work, and volunteer work is 0.'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_amount__isnull', True), ('cost_amount__gte', 0), _connector='OR'), name='finance_item_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('employer_contributions__isnull', True), ('form', 'ZLECENIE'), _connector='OR'), name='finance_item_contributions_zlecenie_only', violation_error_message='Employer contributions apply to a contract of mandate only.'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('in_kind_hourly_rate__isnull', True), ('in_kind_hours__isnull', True)), ('form', 'VOLUNTEER'), _connector='OR'), name='finance_item_in_kind_volunteer_only', violation_error_message='Volunteer hours apply to volunteer work only.'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('paid_on__isnull', True), ('kind', 'EXPENSE'), ('contract_amount__gt', 0), _connector='OR'), name='finance_item_paid_is_priced', violation_error_message='Only a priced, non-volunteer fee can be paid.'),
        ),
    ]
