# Generated by Django 6.0.4 on 2026-09-23 17:37

import django.db.models.deletion
import finance.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # No dependency on the roster's latest migration: nothing here touches a
    # roster table, and the roster-copy test rolls the roster back past 0062
    # while this migration stays applied.
    dependencies = [
        ('finance', '0002_copy_roster_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(max_length=200, upload_to=finance.models.attachment_upload_to, verbose_name='File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Original name')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='Size in bytes')),
            ],
            options={
                'verbose_name': 'Finance attachment',
                'verbose_name_plural': 'Finance attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='costitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='document_type',
            field=models.CharField(blank=True, choices=[('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('RECEIPT', 'Receipt'), ('OTHER', 'Other document')], max_length=8, verbose_name='Document type'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vendor'),
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('PERSONNEL_ARTISTIC', 'Artistic personnel'), ('PERSONNEL_TECHNICAL', 'Technical personnel'), ('VENUE', 'Venue'), ('TRAVEL', 'Travel'), ('ACCOMMODATION', 'Accommodation'), ('CATERING', 'Catering'), ('MATERIALS', 'Materials and rights'), ('EQUIPMENT', 'Equipment'), ('PROMOTION', 'Promotion'), ('RECORDING', 'Recording'), ('ADMINISTRATION', 'Administration'), ('OTHER', 'Other')], max_length=24, verbose_name='Category')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('unit', models.CharField(choices=[('PERSON', 'Person'), ('PIECE', 'Piece'), ('SERVICE', 'Service'), ('HOUR', 'Hour'), ('DAY', 'Day'), ('NIGHT', 'Night'), ('KM', 'Kilometre'), ('LUMP_SUM', 'Lump sum')], max_length=10, verbose_name='Unit')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit cost')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.projectbudget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Budget line',
                'verbose_name_plural': 'Budget lines',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='costitem',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_items', to='finance.budgetline', verbose_name='Plan line'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ('PERSONNEL_ARTISTIC', 'PERSONNEL_TECHNICAL')), ('kind', 'FEE')), models.Q(('kind', 'EXPENSE'), models.Q(('category__in', ('PERSONNEL_ARTISTIC', 'PERSONNEL_TECHNICAL')), _negated=True)), _connector='OR'), name='finance_item_category_matches_kind', violation_error_message='Personnel costs are fees; every other category is an expense.'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'FEE'), models.Q(('contract_amount__isnull', True), ('cost_amount__gt', 0), ('crew_assignment__isnull', True), ('form', ''), ('participation__isnull', True)), _connector='OR'), name='finance_item_expense_shape', violation_error_message='An expense carries its cost directly and belongs to no person.'),
        ),
        migrations.AddField(
            model_name='financeattachment',
            name='cost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.costitem', verbose_name='Cost item'),
        ),
        migrations.AddField(
            model_name='financeattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='finance_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='finance_line_unit_cost_not_negative'),
        ),
    ]
