# Generated by Django 6.0.4 on 2026-09-23 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_plan_expenses_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeevent',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.projectbudget', verbose_name='Budget'),
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('PUBLIC_GRANT', 'Public grant'), ('PRIVATE_GRANT', 'Private grant'), ('SPONSOR', 'Sponsor'), ('DONATIONS', 'Donations'), ('TICKETS', 'Tickets'), ('OWN_FUNDS', 'Own funds'), ('IN_KIND', 'Contribution in kind'), ('VOLUNTEER_WORK', 'Volunteer work')], max_length=16, verbose_name='Kind')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('grantor', models.CharField(blank=True, max_length=200, verbose_name='Grantor')),
                ('agreement_number', models.CharField(blank=True, max_length=100, verbose_name='Agreement number')),
                ('agreement_date', models.DateField(blank=True, null=True, verbose_name='Agreement date')),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Awarded amount')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('APPLIED', 'Applied for'), ('AWARDED', 'Awarded'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], default='PLANNED', max_length=10, verbose_name='Status')),
                ('eligible_from', models.DateField(blank=True, null=True, verbose_name='Eligible from')),
                ('eligible_to', models.DateField(blank=True, null=True, verbose_name='Eligible to')),
                ('report_due_on', models.DateField(blank=True, null=True, verbose_name='Report due on')),
                ('required_own_share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Required own share (%)')),
                ('admin_cost_cap_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Administration cap (%)')),
                ('line_tolerance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Line tolerance (%)')),
                ('document_note_template', models.TextField(default='Wydatek w kwocie {document_amount} zł (dokument nr {document_number}) został sfinansowany w kwocie {source_amount} zł ze środków: {source_name}, zgodnie z umową nr {agreement_number} z dnia {agreement_date}. Pozycja kosztorysu: {plan_line}.', verbose_name='Document note template')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Funding source',
                'verbose_name_plural': 'Funding sources',
                'ordering': ['name', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('awarded_amount__isnull', True), ('awarded_amount__gte', 0), _connector='OR'), name='finance_source_awarded_not_negative'), models.CheckConstraint(condition=models.Q(('eligible_from__isnull', True), ('eligible_to__isnull', True), ('eligible_from__lte', models.F('eligible_to')), _connector='OR'), name='finance_source_eligibility_ordered', violation_error_message='The eligibility period ends before it starts.'), models.CheckConstraint(condition=models.Q(('required_own_share_pct__isnull', True), models.Q(('required_own_share_pct__gte', 0), ('required_own_share_pct__lte', 100)), _connector='OR'), name='finance_source_required_own_share_pct_range'), models.CheckConstraint(condition=models.Q(('admin_cost_cap_pct__isnull', True), models.Q(('admin_cost_cap_pct__gte', 0), ('admin_cost_cap_pct__lte', 100)), _connector='OR'), name='finance_source_admin_cost_cap_pct_range'), models.CheckConstraint(condition=models.Q(('line_tolerance_pct__isnull', True), models.Q(('line_tolerance_pct__gte', 0), ('line_tolerance_pct__lte', 100)), _connector='OR'), name='finance_source_line_tolerance_pct_range')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Planned amount')),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Received amount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundings', to='finance.projectbudget', verbose_name='Budget')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundings', to='finance.fundingsource', verbose_name='Funding source')),
            ],
            options={
                'verbose_name': 'Project funding',
                'verbose_name_plural': 'Project fundings',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.budgetline', verbose_name='Plan line')),
                ('project_funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_allocations', to='finance.projectfunding', verbose_name='Funding')),
            ],
            options={
                'verbose_name': 'Line allocation',
                'verbose_name_plural': 'Line allocations',
            },
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.costitem', verbose_name='Cost item')),
                ('project_funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.projectfunding', verbose_name='Funding')),
            ],
            options={
                'verbose_name': 'Cost allocation',
                'verbose_name_plural': 'Cost allocations',
            },
        ),
        migrations.AddConstraint(
            model_name='projectfunding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('budget', 'source'), name='finance_funding_unique_source_per_budget', violation_error_message='The source is already on this project.'),
        ),
        migrations.AddConstraint(
            model_name='projectfunding',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0), ('received_amount__gte', 0)), name='finance_funding_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='lineallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('budget_line', 'project_funding'), name='finance_line_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='lineallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_line_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cost_item', 'project_funding'), name='finance_cost_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_cost_allocation_positive'),
        ),
    ]
