# Generated by Django 6.0.4 on 2026-09-30 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_costitem_paid_before_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('html', models.TextField(verbose_name='Document')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='finance.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Contract snapshot',
                'verbose_name_plural': 'Contract snapshots',
            },
        ),
    ]
