# Generated by Django 6.0.4 on 2026-09-30 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_contract_snapshot'),
        ('roster', '0069_trip_plan_days_joins_on_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='receipt_has_buyer_nip',
            field=models.BooleanField(default=False, verbose_name="Receipt bears the foundation's NIP"),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='document_type',
            field=models.CharField(blank=True, choices=[('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('RECEIPT', 'Receipt'), ('OTHER', 'Other document'), ('NONE', 'No document')], max_length=8, verbose_name='Document type'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_has_buyer_nip', False), ('document_type', 'RECEIPT'), _connector='OR'), name='finance_item_buyer_nip_receipt_only', violation_error_message="Only a receipt is marked as bearing the foundation's NIP."),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type', 'NONE'), _negated=True), models.Q(('document_date__isnull', True), ('document_number', '')), _connector='OR'), name='finance_item_no_document_is_bare', violation_error_message='An expense without a document has no document number or date.'),
        ),
    ]
