# Generated by Django 6.0.2 on 2026-05-14 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Donor Email')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross donation amount in PLN.', max_digits=10, verbose_name='Amount (PLN)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10, verbose_name='Status')),
                ('axepta_payment_id', models.CharField(blank=True, db_index=True, help_text='Gateway-side payment identifier, captured from the webhook when available.', max_length=255, null=True, verbose_name='Axepta Payment ID')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
