# Generated by Django 6.0.2 on 2026-05-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Polish Złoty'), ('EUR', 'Euro')], db_index=True, default='PLN', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Gross donation amount, expressed in `currency`.', max_digits=10, verbose_name='Amount'),
        ),
    ]
