# Generated by Django 6.0.4 on 2026-06-03 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_donation_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('ACTIVE', 'Active patron'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', max_length=10, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Internal note')),
            ],
            options={
                'verbose_name': 'Patron Lead',
                'verbose_name_plural': 'Patron Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='payments_patron_isdel_idx')],
            },
        ),
    ]
