# Generated by Django 6.0.2 on 2026-04-11 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal display name, e.g., 'National Philharmonic' or 'Conductor's Room'", max_length=255)),
                ('category', models.CharField(choices=[('CONCERT_HALL', 'Concert Hall'), ('REHEARSAL_ROOM', 'Rehearsal Room'), ('HOTEL', 'Hotel'), ('AIRPORT', 'Airport'), ('TRANSIT_STATION', 'Transit Station'), ('WORKSPACE', 'Private Workspace'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('google_place_id', models.CharField(blank=True, help_text='Unique identifier from Google Places API. Null for private/custom locations.', max_length=255, null=True, unique=True)),
                ('formatted_address', models.TextField(help_text='Full official address or precise custom description.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone string, e.g., 'Europe/Warsaw'. Updated via external service.", max_length=100)),
                ('internal_notes', models.TextField(blank=True, help_text="Internal logistics instructions, e.g., 'Gate code: 1234', 'Backstage entrance'.")),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this location is available for new projects. Use instead of deletion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'logistics_location',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='logistics_l_categor_f0fe8f_idx')],
            },
        ),
    ]
