# Generated by Django 6.0.2 on 2026-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Unique identifier from Google Places API. Null for private/custom locations.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('google_place_id__isnull', False)), fields=('google_place_id',), name='unique_active_google_place_id'),
        ),
    ]
