# Generated by Django 6.0.2 on 2026-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_location_google_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Unique identifier from Google Places API. Null for private/custom locations.', max_length=512, null=True),
        ),
    ]
