# Generated by Django 6.0.2 on 2026-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_location_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('CONCERT_HALL', 'Concert Hall'), ('CHURCH', 'Church'), ('REHEARSAL_ROOM', 'Rehearsal Room'), ('HOTEL', 'Hotel'), ('AIRPORT', 'Airport'), ('TRANSIT_STATION', 'Transit Station'), ('WORKSPACE', 'Private Workspace'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
    ]
