# Generated by Django 6.0.4 on 2026-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_location_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('CONCERT_HALL', 'Concert Hall'), ('CHURCH', 'Church'), ('REHEARSAL_ROOM', 'Rehearsal Room'), ('HOTEL', 'Hotel'), ('AIRPORT', 'Airport'), ('TRANSIT_STATION', 'Transit Station'), ('RESTAURANT', 'Restaurant'), ('PARKING', 'Car park'), ('WORKSPACE', 'Private Workspace'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
    ]
