# Generated by Django 6.0.2 on 2026-04-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentcategory',
            name='documents_d_allowed_84dbb0_gin',
        ),
        migrations.RemoveIndex(
            model_name='documentcategory',
            name='documents_d_is_dele_932943_idx',
        ),
    ]
