# Generated by Django 6.0.2 on 2026-02-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Rok urodzenia')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Rok śmierci')),
            ],
            options={
                'verbose_name': 'Kompozytor',
                'verbose_name_plural': 'Kompozytorzy',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł utworu')),
                ('voicing', models.CharField(blank=True, max_length=50, verbose_name='Obsada wokalna (np. SATB)')),
                ('description', models.TextField(blank=True, verbose_name='Uwagi / Opis')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='archive.composer', verbose_name='Kompozytor')),
            ],
            options={
                'verbose_name': 'Utwór',
                'verbose_name_plural': 'Utwory',
            },
        ),
    ]
