# Generated by Django 6.0.2 on 2026-02-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_piece_sheet_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_part', models.CharField(choices=[('SOPRAN', 'Sopran'), ('SOPRAN_1', 'Sopran 1'), ('SOPRAN_2', 'Sopran 2'), ('ALT', 'Alt'), ('ALT_1', 'Alt 1'), ('ALT_2', 'Alt 2'), ('TENOR', 'Tenor'), ('TENOR_1', 'Tenor 1'), ('TENOR_2', 'Tenor 2'), ('BAS', 'Bas'), ('BAS_1', 'Bas 1'), ('BAS_2', 'Bas 2'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament (Pianino)')], max_length=20, verbose_name='Głos / Partia')),
                ('audio_file', models.FileField(upload_to='audio_tracks/', verbose_name='Plik Audio (MIDI/MP3)')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.piece', verbose_name='Utwór')),
            ],
            options={
                'verbose_name': 'Ścieżka dźwiękowa',
                'verbose_name_plural': 'Ścieżki dźwiękowe',
            },
        ),
    ]
