# Generated by Django 6.0.2 on 2026-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repertoire',
            field=models.ManyToManyField(blank=True, related_name='projects', to='archive.piece', verbose_name='Repertuar (Utwory)'),
        ),
    ]
