# Generated by Django 6.0.2 on 2026-03-14 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma / Marka')),
                ('specialty', models.CharField(choices=[('SOUND', 'Reżyseria Dźwięku'), ('LIGHT', 'Reżyseria Świateł'), ('VISUALS', 'Sztuka Wizualna'), ('INSTRUMENT', 'Instrumentalista'), ('LOGISTICS', 'Logistyka'), ('OTHER', 'Inne')], default='OTHER', max_length=15, verbose_name='Specjalizacja')),
            ],
            options={
                'verbose_name': 'Współtwórca (Crew)',
                'verbose_name_plural': 'Współtwórcy',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa Projektu')),
                ('start_date', models.DateField(verbose_name='Data Rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data Zakończenia')),
                ('call_time', models.DateTimeField(blank=True, help_text='Godzina zbiórki', null=True, verbose_name='Call Time')),
                ('dress_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dress Code')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokalizacja')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('voice_type', models.CharField(choices=[('SOP', 'Sopran'), ('MEZ', 'Mezzosopran'), ('ALT', 'Alt'), ('CT', 'Kontratenor'), ('TEN', 'Tenor'), ('BAR', 'Baryton'), ('BAS', 'Bas'), ('DIR', 'Dyrygent/Kierownik')], max_length=5, verbose_name='Rodzaj głosu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('sight_reading_skill', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Czytanie a vista (1-5)')),
                ('vocal_range_bottom', models.CharField(blank=True, help_text='np. G2', max_length=5, null=True, verbose_name='Skala (dół)')),
                ('vocal_range_top', models.CharField(blank=True, help_text='np. C5', max_length=5, null=True, verbose_name='Skala (góra)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Artysta',
                'verbose_name_plural': 'Artyści',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('INV', 'Zaproszony'), ('CON', 'Potwierdzony'), ('DEC', 'Odrzucił')], default='INV', max_length=3, verbose_name='Status')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Wynagrodzenie')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='roster.artist', verbose_name='Artysta')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='roster.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Uczestnictwo',
                'verbose_name_plural': 'Uczestnictwa',
            },
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('role_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zakres obowiązków')),
                ('status', models.CharField(choices=[('INV', 'Wstępnie umówiony'), ('CON', 'Potwierdzony')], default='INV', max_length=3, verbose_name='Status')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Wynagrodzenie')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.collaborator', verbose_name='Współtwórca')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='roster.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Przydział Współtwórcy',
                'verbose_name_plural': 'Przydziały Współtwórców',
            },
        ),
        migrations.CreateModel(
            name='ProjectPieceCasting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('voice_line', models.CharField(choices=[('S1', 'Sopran 1'), ('S2', 'Sopran 2'), ('A1', 'Alt 1'), ('A2', 'Alt 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bas 1'), ('B2', 'Bas 2'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament'), ('PRON', 'Wymowa (Dykcja/Język)')], max_length=5, verbose_name='Linia melodyczna (Divisi)')),
                ('role', models.CharField(choices=[('TUTTI', 'Tutti'), ('SOLO', 'Partia Solowa'), ('BACK', 'Chórek')], default='TUTTI', max_length=10, verbose_name='Rola')),
                ('gives_pitch', models.BooleanField(default=False, verbose_name='Daje dźwięk (Kamerton)')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notatki')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='roster.participation', verbose_name='Uczestnik')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='archive.piece', verbose_name='Utwór')),
            ],
            options={
                'verbose_name': 'Obsada Utworu',
                'verbose_name_plural': 'Obsady Utworów',
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_time', models.DateTimeField(verbose_name='Data i godzina')),
                ('location', models.CharField(max_length=200, verbose_name='Sala prób')),
                ('focus', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cel próby')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obowiązkowa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='roster.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Próba',
                'verbose_name_plural': 'Próby',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Obecny'), ('LATE', 'Spóźniony'), ('ABSENT', 'Nieobecny'), ('EXCUSED', 'Usprawiedliwiony')], default='PRESENT', max_length=10, verbose_name='Status')),
                ('minutes_late', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minuty spóźnienia')),
                ('excuse_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Powód nieobecności (Notatka chórzysty)')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='roster.participation', verbose_name='Uczestnik')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='roster.rehearsal', verbose_name='Próba')),
            ],
            options={
                'verbose_name': 'Obecność',
                'verbose_name_plural': 'Obecności',
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(verbose_name='Kolejność w programie (1, 2, 3...)')),
                ('is_encore', models.BooleanField(default=False, verbose_name='Czy to BIS?')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.piece', verbose_name='Utwór')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='roster.project')),
            ],
            options={
                'verbose_name': 'Pozycja w Programie',
                'verbose_name_plural': 'Program Koncertu (Setlista)',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('project', 'order'), name='unique_order_per_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('artist', 'project'), name='unique_project_participation'),
        ),
        migrations.AddConstraint(
            model_name='crewassignment',
            constraint=models.UniqueConstraint(fields=('collaborator', 'project'), name='unique_crew_assignment'),
        ),
        migrations.AddConstraint(
            model_name='projectpiececasting',
            constraint=models.UniqueConstraint(fields=('participation', 'piece'), name='unique_piece_casting'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('rehearsal', 'participation'), name='unique_rehearsal_attendance'),
        ),
    ]
