# Generated by Django 6.0.2 on 2026-02-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('voice_part', models.CharField(choices=[('S', 'Sopran'), ('A', 'Alt'), ('T', 'Tenor'), ('B', 'Bas'), ('C', 'Dyrygent')], max_length=1, verbose_name='Głos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Artysta',
                'verbose_name_plural': 'Artyści',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa Projektu')),
                ('start_date', models.DateField(verbose_name='Data Rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data Zakończenia')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokalizacja')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INV', 'Zaproszony'), ('CON', 'Potwierdzony'), ('DEC', 'Odrzucił')], default='INV', max_length=3, verbose_name='Status')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Wynagrodzenie (PLN)')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='roster.artist', verbose_name='Artysta')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='roster.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Uczestnictwo',
                'verbose_name_plural': 'Uczestnictwa',
                'unique_together': {('artist', 'project')},
            },
        ),
    ]
