# Generated by Django 6.0.2 on 2026-03-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_track_piece'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='roster.participation', verbose_name='Uczestnik'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='rehearsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='roster.rehearsal', verbose_name='Próba'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='roster.collaborator', verbose_name='Współtwórca'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='crew_assignments', to='roster.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participations', to='roster.artist', verbose_name='Artysta'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participations', to='roster.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='archive.piece', verbose_name='Utwór'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='program_items', to='roster.project'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='castings', to='roster.participation', verbose_name='Uczestnik'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='castings', to='archive.piece', verbose_name='Utwór'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rehearsals', to='roster.project', verbose_name='Projekt'),
        ),
    ]
