# Generated by Django 6.0.2 on 2026-03-16 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_alter_attendance_participation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data i godzina wydarzenia'),
        ),
    ]
