# Generated by Django 6.0.2 on 2026-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Szkic / Planowany'), ('ACTIVE', 'W przygotowaniu'), ('DONE', 'Zrealizowany'), ('CANC', 'Anulowany')], default='DRAFT', max_length=10, verbose_name='Status'),
        ),
    ]
