# Generated by Django 6.0.2 on 2026-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_project_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectpiececasting',
            name='unique_piece_casting',
        ),
    ]
