# Generated by Django 6.0.2 on 2026-02-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_alter_artist_voice_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='voice_part',
            field=models.CharField(choices=[('SOPRAN', 'Sopran'), ('SOPRAN_1', 'Sopran 1'), ('SOPRAN_2', 'Sopran 2'), ('ALT', 'Alt'), ('ALT_1', 'Alt 1'), ('ALT_2', 'Alt 2'), ('TENOR', 'Tenor'), ('TENOR_1', 'Tenor 1'), ('TENOR_2', 'Tenor 2'), ('BAS', 'Bas'), ('BAS_1', 'Bas 1'), ('BAS_2', 'Bas 2'), ('DYRYGENT', 'Dyrygent')], max_length=8, verbose_name='Głos'),
        ),
    ]
