# Generated by Django 6.0.2 on 2026-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_artist_voice_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Wynagrodzenie (PLN)'),
        ),
    ]
