# Generated by Django 6.0.2 on 2026-03-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_remove_projectpiececasting_unique_piece_casting'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='invited_participations',
            field=models.ManyToManyField(blank=True, related_name='invited_rehearsals', to='roster.participation', verbose_name='Wezwani chórzyści'),
        ),
    ]
