# Generated by Django 6.0.2 on 2026-03-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_rehearsal_invited_participations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='run_sheet',
            field=models.JSONField(blank=True, default=list, verbose_name='Harmonogram Dnia (Run-sheet)'),
        ),
    ]
