# Generated by Django 6.0.2 on 2026-03-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_project_run_sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewassignment',
            options={'verbose_name': 'Przypisanie ekipy', 'verbose_name_plural': 'Przypisania ekipy'},
        ),
        migrations.RemoveConstraint(
            model_name='crewassignment',
            name='unique_crew_assignment',
        ),
        migrations.RemoveField(
            model_name='programitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='programitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projectpiececasting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectpiececasting',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='projectpiececasting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='artist',
            name='voice_type',
            field=models.CharField(choices=[('SOP', 'Sopran'), ('MEZ', 'Mezzosopran'), ('ALT', 'Alt'), ('CT', 'Kontratenor'), ('TEN', 'Tenor'), ('BAR', 'Baryton'), ('BAS', 'Bas'), ('DIR', 'Dyrygent')], max_length=5, verbose_name='Rodzaj głosu'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.collaborator', verbose_name='Współtwórca'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Stawka (PLN)'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='roster.project', verbose_name='Projekt'),
        ),
        migrations.RemoveField(
            model_name='crewassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crewassignment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='crewassignment',
            name='updated_at',
        ),
    ]
