# Generated by Django 6.0.2 on 2026-03-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_alter_crewassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
    ]
