# Generated by Django 6.0.2 on 2026-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_remove_projectpiececasting_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='vocal_range_bottom',
            field=models.CharField(blank=True, default='', help_text='np. G2', max_length=5, verbose_name='Skala (dół)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='vocal_range_top',
            field=models.CharField(blank=True, default='', help_text='np. C5', max_length=5, verbose_name='Skala (góra)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='excuse_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Powód nieobecności (Notatka chórzysty)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Firma / Marka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stawka (PLN)'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='role_description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Zakres obowiązków'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participation',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Wynagrodzenie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='dress_code_female',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dress Code (Kobiety)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='dress_code_male',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dress Code (Mężczyźni)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lokalizacja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='spotify_playlist_url',
            field=models.URLField(blank=True, default='', help_text='Link do playlisty Spotify', verbose_name='Playlista (Spotify)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Notatki'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='focus',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cel próby'),
            preserve_default=False,
        ),
    ]
