# Generated by Django 6.0.2 on 2026-04-08 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_alter_composer_options_alter_piece_options_and_more'),
        ('roster', '0012_alter_artist_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Collaborator (Crew)', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.AlterModelOptions(
            name='crewassignment',
            options={'verbose_name': 'Crew Assignment', 'verbose_name_plural': 'Crew Assignments'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
        migrations.AlterModelOptions(
            name='programitem',
            options={'ordering': ['order'], 'verbose_name': 'Program Item', 'verbose_name_plural': 'Concert Program (Setlist)'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectpiececasting',
            options={'verbose_name': 'Piece Casting', 'verbose_name_plural': 'Piece Castings'},
        ),
        migrations.AlterModelOptions(
            name='rehearsal',
            options={'ordering': ['date_time'], 'verbose_name': 'Rehearsal', 'verbose_name_plural': 'Rehearsals'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='sight_reading_skill',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Sight Reading Skill (1-5)'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='vocal_range_bottom',
            field=models.CharField(blank=True, help_text='e.g. G2', max_length=5, verbose_name='Range (Bottom)'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='vocal_range_top',
            field=models.CharField(blank=True, help_text='e.g. C5', max_length=5, verbose_name='Range (Top)'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='voice_type',
            field=models.CharField(choices=[('SOP', 'Soprano'), ('MEZ', 'Mezzo-Soprano'), ('ALT', 'Alto'), ('CT', 'Countertenor'), ('TEN', 'Tenor'), ('BAR', 'Baritone'), ('BAS', 'Bass'), ('DIR', 'Conductor')], max_length=5, verbose_name='Voice Type'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='excuse_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Excuse Note'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='minutes_late',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minutes Late'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='roster.participation', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='rehearsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='roster.rehearsal', verbose_name='Rehearsal'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company / Brand'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='specialty',
            field=models.CharField(choices=[('SOUND', 'Sound Engineering'), ('LIGHT', 'Lighting Design'), ('VISUALS', 'Visual Arts'), ('INSTRUMENT', 'Instrumentalist'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], default='OTHER', max_length=15, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.collaborator', verbose_name='Collaborator'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='roster.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='role_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Role Description'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='status',
            field=models.CharField(choices=[('INV', 'Tentatively Booked'), ('CON', 'Confirmed')], default='INV', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participations', to='roster.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participations', to='roster.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('INV', 'Invited'), ('CON', 'Confirmed'), ('DEC', 'Declined')], default='INV', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='is_encore',
            field=models.BooleanField(default=False, verbose_name='Is Encore?'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='archive.piece', verbose_name='Piece'),
        ),
        migrations.AlterField(
            model_name='project',
            name='call_time',
            field=models.DateTimeField(blank=True, help_text='Call time for performers', null=True, verbose_name='Call Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date & Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dress_code_female',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dress Code (Female)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dress_code_male',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dress Code (Male)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='run_sheet',
            field=models.JSONField(blank=True, default=list, verbose_name='Run-sheet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='spotify_playlist_url',
            field=models.URLField(blank=True, help_text='Spotify playlist URL', verbose_name='Spotify Playlist'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / Planned'), ('ACTIVE', 'Active / In Prep'), ('DONE', 'Completed'), ('CANC', 'Cancelled')], default='DRAFT', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='gives_pitch',
            field=models.BooleanField(default=False, verbose_name='Gives Pitch (Tuning Fork)'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='castings', to='roster.participation', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='castings', to='archive.piece', verbose_name='Piece'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=5, verbose_name='Voice Line (Divisi)'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='focus',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rehearsal Focus'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='invited_participations',
            field=models.ManyToManyField(blank=True, related_name='invited_rehearsals', to='roster.participation', verbose_name='Invited Singers'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Is Mandatory'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Rehearsal Venue'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rehearsals', to='roster.project', verbose_name='Project'),
        ),
    ]
