# Generated by Django 6.0.2 on 2026-04-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_piecevoicerequirement_unique_together_and_more'),
        ('roster', '0013_alter_artist_options_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participation',
            name='unique_project_participation',
        ),
        migrations.AlterField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked authentication identity. SET_NULL preserves historical HR data if account is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['rehearsal', 'status'], name='roster_atte_rehears_a85bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='crewassignment',
            index=models.Index(fields=['project', 'status'], name='roster_crew_project_90457f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'date_time'], name='roster_proj_status_b1158f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpiececasting',
            index=models.Index(fields=['participation', 'piece'], name='roster_proj_partici_e6ea13_idx'),
        ),
        migrations.AddIndex(
            model_name='rehearsal',
            index=models.Index(fields=['project', 'date_time'], name='roster_rehe_project_fc25dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_active_artist_email'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('email__isnull', False)), fields=('email',), name='unique_active_collaborator_email'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('artist', 'project'), name='unique_active_project_participation'),
        ),
    ]
