# Generated by Django 6.0.2 on 2026-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_project_timezone_rehearsal_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timezone',
            field=models.CharField(default='Europe/Warsaw', help_text="Local timezone for this project's primary location. Critical for UI rendering and iCal feeds.", max_length=63),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='timezone',
            field=models.CharField(default='Europe/Warsaw', help_text='Local timezone for this specific rehearsal. Essential for tours crossing multiple timezones.', max_length=63),
        ),
    ]
