# Generated by Django 6.0.2 on 2026-04-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('roster', '0016_alter_project_timezone_alter_rehearsal_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary location for the project. Dictates the default timezone.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='logistics.location'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Specific location for this rehearsal. Overrides project default if needed.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rehearsals', to='logistics.location'),
        ),
    ]
