# Generated by Django 6.0.2 on 2026-04-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0017_alter_project_location_alter_rehearsal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='The Maestro leading this project.', limit_choices_to={'voice_type': 'DIR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_projects', to='roster.artist', verbose_name='Conductor'),
        ),
    ]
