# Generated by Django 6.0.4 on 2026-06-12 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_alter_piece_lyrics_original'),
        ('roster', '0020_project_score_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('READY', 'Ready / Knows the part')], default='NOT_STARTED', max_length=12, verbose_name='Readiness')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_readiness', to='roster.participation', verbose_name='Participant')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_entries', to='archive.piece', verbose_name='Piece')),
            ],
            options={
                'verbose_name': 'Piece Readiness',
                'verbose_name_plural': 'Piece Readiness',
                'indexes': [models.Index(fields=['participation', 'piece'], name='roster_piec_partici_eb5290_idx')],
                'constraints': [models.UniqueConstraint(fields=('participation', 'piece'), name='unique_participation_piece_readiness')],
            },
        ),
    ]
