# Generated by Django 6.0.4 on 2026-06-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0021_piecereadiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewassignment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the agreed fee for this assignment has been settled.', verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='crewassignment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp the fee was marked as settled. Cleared if the payment is reverted.', null=True, verbose_name='Paid At'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the agreed fee for this participation has been settled.', verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='participation',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp the fee was marked as settled. Cleared if the payment is reverted.', null=True, verbose_name='Paid At'),
        ),
    ]
