# Generated by Django 6.0.4 on 2026-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0022_crewassignment_is_paid_crewassignment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the automated upcoming-event reminder was dispatched. Null = not yet sent.', null=True),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the automated upcoming-rehearsal reminder was dispatched. Null = not yet sent.', null=True),
        ),
    ]
