# Generated by Django 6.0.4 on 2026-06-26 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0023_project_reminder_sent_at_rehearsal_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('density_mode', models.CharField(choices=[('CONCERT', 'Concert — frontispiece per piece'), ('MASS', 'Mass — light dividers, consolidated texts')], default='CONCERT', max_length=8, verbose_name='Density Mode')),
                ('include_title_page', models.BooleanField(default=True, verbose_name='Title Page')),
                ('include_toc', models.BooleanField(default=True, verbose_name='Table of Contents')),
                ('include_page_numbers', models.BooleanField(default=True, verbose_name='Page Numbers')),
                ('include_bookmarks', models.BooleanField(default=True, verbose_name='PDF Bookmarks')),
                ('normalize_to_a4', models.BooleanField(default=True, help_text="Scale and centre every source page onto a uniform A4 sheet so the assembled book does not 'wobble' between differently-sized editions.", verbose_name='Normalize to A4')),
                ('status', models.CharField(choices=[('IDLE', 'Not generated'), ('QUED', 'Queued'), ('BLDG', 'Building'), ('RDY', 'Ready'), ('FAIL', 'Failed')], db_index=True, default='IDLE', max_length=4, verbose_name='Build Status')),
                ('error', models.TextField(blank=True, verbose_name='Build Error')),
                ('source_hash', models.CharField(blank=True, help_text='SHA-256 of the inputs (ordered repertoire, chosen editions, settings) that produced the current score_pdf. The output is stale when the live hash differs from this value.', max_length=64, verbose_name='Source Hash')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generated At')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_package', to='roster.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Score Package',
                'verbose_name_plural': 'Score Packages',
            },
        ),
    ]
