# Generated by Django 6.0.4 on 2026-06-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0024_scorepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepackage',
            name='card_include_program_note',
            field=models.BooleanField(default=True, verbose_name='Card: Programme Note'),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='card_include_text',
            field=models.BooleanField(default=True, verbose_name='Card: Original Text'),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='card_include_translation',
            field=models.BooleanField(default=True, verbose_name='Card: Translation'),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='include_cards',
            field=models.BooleanField(default=True, help_text='Render per-piece text content (frontispiece in CONCERT mode, consolidated texts section in MASS mode).', verbose_name='Include Text Content'),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='translation_language',
            field=models.CharField(default='pl', help_text='ISO 639-1 code of the translation/programme-note language shown on the cards.', max_length=8, verbose_name='Card Language'),
        ),
    ]
