# Generated by Django 6.0.4 on 2026-06-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_annotation_payload_helptext'),
        ('roster', '0025_scorepackage_card_include_program_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='card_elements',
            field=models.JSONField(blank=True, help_text="Explicit list of card element keys to render for this item. Null = derive from the package's card toggles.", null=True, verbose_name='Card Elements'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='card_enabled',
            field=models.BooleanField(blank=True, help_text="Per-item override of the package's card master switch. Null = inherit.", null=True, verbose_name='Card Enabled'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='note_override',
            field=models.TextField(blank=True, help_text="Replaces the programme note on this item's card for this concert.", verbose_name='Note Override'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='pdf_page_end',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-based last source page to bind (inclusive). Blank = last page.', null=True, verbose_name='PDF Page End'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='pdf_page_start',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-based first source page to bind (trims publisher front matter). Blank = page 1.', null=True, verbose_name='PDF Page Start'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='role_prefix',
            field=models.CharField(blank=True, help_text="Liturgical/role prefix shown before the title, e.g. 'Ofiarowanie:'.", max_length=60, verbose_name='Role Prefix'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='score_edition',
            field=models.ForeignKey(blank=True, help_text='Explicit edition to bind for this piece. Blank = auto-select the default edition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archive.scoreedition', verbose_name='Score Edition'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='section_label',
            field=models.CharField(blank=True, help_text="Section heading shown as the card eyebrow, e.g. 'LITURGIA EUCHARYSTYCZNA'. Blank = the piece's text source.", max_length=80, verbose_name='Section Label'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='text_override',
            field=models.TextField(blank=True, help_text="Replaces the original text on this item's card for this concert.", verbose_name='Text Override'),
        ),
    ]
