# Generated by Django 6.0.4 on 2026-06-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0026_programitem_card_elements_programitem_card_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepackage',
            name='build_version',
            field=models.PositiveIntegerField(default=0, help_text='Increments on every successful build, so a printed/distributed copy can be reconciled against the live book.', verbose_name='Build Version'),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='distributed_at',
            field=models.DateTimeField(blank=True, help_text='When a non-manager (singer) first downloaded the current build. Null until the book leaves the building; reset on every rebuild.', null=True, verbose_name='First Distributed At'),
        ),
    ]
