# Generated by Django 6.0.4 on 2026-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0027_scorepackage_build_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepackage',
            name='is_manual_upload',
            field=models.BooleanField(default=False, help_text="True when the current score_pdf was hand-uploaded by the conductor rather than assembled by the generator. The cockpit then shows 'manually uploaded' instead of a (meaningless) build version / staleness, and the two paths stop fighting over project.score_pdf.", verbose_name='Manually Uploaded'),
        ),
    ]
