# Generated by Django 6.0.4 on 2026-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0028_scorepackage_is_manual_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepackage',
            name='duplex_mode',
            field=models.BooleanField(default=False, help_text='Lay the book out for double-sided printing: the page number moves to the outer bottom corner (recto-right / verso-left) behind a white knockout for legibility, and — in Concert density — every piece opens on a right-hand page (a blank verso is inserted where needed).', verbose_name='Double-sided print'),
        ),
    ]
