# Generated by Django 6.0.4 on 2026-07-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_translation_translator'),
        ('roster', '0029_scorepackage_duplex_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='performers',
            field=models.CharField(blank=True, help_text="Concert-specific performers line for the card, e.g. 'Sopran solo: J. Kowalska · organy: A. Nowak'.", max_length=200, verbose_name='Performers'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='translation',
            field=models.ForeignKey(blank=True, help_text="Explicit translation to print on this item's card. Blank = auto-select in the package language (literal preferred).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archive.translation', verbose_name='Pinned Translation'),
        ),
    ]
