# Generated by Django 6.0.4 on 2026-07-21 23:57

from django.db import migrations, models
from django.db.models import F


def backfill_activation_sent_at(apps, schema_editor):
    """Existing artists received their invite at provisioning, so `created_at` is
    an accurate stand-in for when it was sent. Seed it so already-invited singers
    show a send date immediately, rather than a blank until the next resend."""
    Artist = apps.get_model('roster', 'Artist')
    Artist.objects.filter(activation_email_sent_at__isnull=True).update(
        activation_email_sent_at=F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0031_scorepackage_card_default_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='activation_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the account-activation invite was last dispatched — at initial provisioning or a manual resend. Lets the roster show when the singer was invited and confirm a resend actually went out. Irrelevant once the account is activated.', null=True, verbose_name='Activation Email Sent At'),
        ),
        migrations.RunPython(backfill_activation_sent_at, migrations.RunPython.noop),
    ]
