# Generated by Django 6.0.4 on 2026-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0032_artist_activation_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Roster standing. Owned exclusively by ArtistHRService.archive_artist / restore_artist, which move it in lockstep with `is_deleted` and the account's login gate — never write it directly.", verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
    ]
