# Generated by Django 6.0.4 on 2026-07-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0033_alter_artist_is_active_alter_artist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
    ]
