# Generated by Django 6.0.4 on 2026-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0035_identity_vocative_moves_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='announcement_nudged_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When the managers were last told this project's announcement queue is waiting. Unlike reminder_sent_at this is a cooldown, not a one-shot claim: the sweep re-raises a queue that is still sitting, and a short fuse on urgent news can break through a stamp left by a calm one.", null=True),
        ),
    ]
