# Generated by Django 6.0.4 on 2026-08-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0036_project_announcement_nudged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='hide_source_page_numbers',
            field=models.BooleanField(blank=True, help_text="Per-item override of the package's source-numbering setting. Null = inherit.", null=True, verbose_name="Hide Edition's Page Numbers"),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='hide_source_page_numbers',
            field=models.BooleanField(default=True, help_text="Cover the page numbers the editions print themselves, so the book carries only its own continuous folio. Detected from the PDF's text layer by proving a value that steps by one from page to page; a scanned edition without a text layer is left untouched.", verbose_name="Hide Editions' Own Page Numbers"),
        ),
    ]
