# Generated by Django 6.0.4 on 2026-08-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0037_score_package_source_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dressing_room_note',
            field=models.CharField(blank=True, help_text='Where to change and leave belongings.', max_length=200, verbose_name='Dressing room'),
        ),
        migrations.AddField(
            model_name='project',
            name='entrance_note',
            field=models.CharField(blank=True, help_text="Which door the ensemble uses, e.g. 'side entrance from Rakowiecka, gate 2'.", max_length=200, verbose_name='Entrance / gate'),
        ),
        migrations.AddField(
            model_name='project',
            name='onsite_contact_name',
            field=models.CharField(blank=True, help_text='Who answers on the day — stage manager, sacristan, production.', max_length=120, verbose_name='On-site contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='onsite_contact_phone',
            field=models.CharField(blank=True, help_text="Reachable on the day of the concert. Printed on every sheet, including the singers'.", max_length=32, verbose_name='On-site phone'),
        ),
        migrations.AddField(
            model_name='project',
            name='parking_note',
            field=models.CharField(blank=True, help_text='Where to leave a car, and under what conditions.', max_length=200, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='project',
            name='soundcheck_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Sound check (until)'),
        ),
        migrations.AddField(
            model_name='project',
            name='soundcheck_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Sound check (from)'),
        ),
        migrations.AddField(
            model_name='project',
            name='warmup_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Warm-up (until)'),
        ),
        migrations.AddField(
            model_name='project',
            name='warmup_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Warm-up (from)'),
        ),
    ]
