# Generated by Django 6.0.4 on 2026-08-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0038_project_dressing_room_note_project_entrance_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='liturgical_slot',
            field=models.CharField(blank=True, choices=[('prelude', 'Before Mass'), ('entrance', 'Entrance'), ('kyrie', 'Kyrie'), ('gloria', 'Gloria'), ('psalm', 'Responsorial psalm'), ('acclamation', 'Gospel acclamation'), ('vows', 'Marriage vows'), ('rings', 'Blessing of the rings'), ('intercessions', 'Prayer of the faithful'), ('offertory', 'Offertory'), ('sanctus', 'Sanctus'), ('benedictus', 'Benedictus'), ('agnus_dei', 'Agnus Dei'), ('communion', 'Communion'), ('thanksgiving', 'Thanksgiving'), ('recessional', 'Recessional')], help_text='Where in the Mass this piece belongs. Blank for a concert item.', max_length=24, verbose_name='Liturgical slot'),
        ),
        migrations.AddField(
            model_name='project',
            name='event_kind',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('MASS', 'Mass'), ('WEDDING', 'Wedding Mass'), ('OTHER', 'Other event')], default='CONCERT', help_text='A Mass is programmed against the order of the rite, a concert against a running order.', max_length=12, verbose_name='Event kind'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='role_prefix',
            field=models.CharField(blank=True, help_text='Overrides the line printed before the title. Blank = derived from the liturgical slot.', max_length=60, verbose_name='Role Prefix'),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='section_label',
            field=models.CharField(blank=True, help_text="Overrides the section heading. Blank = the liturgical slot's own part of the rite, or the piece's text source.", max_length=80, verbose_name='Section Label'),
        ),
    ]
