# Generated by Django 6.0.4 on 2026-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0040_backfill_event_kind_from_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpiececasting',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=5, verbose_name='Voice Line (Divisi)'),
        ),
    ]
