# Generated by Django 6.0.4 on 2026-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0043_collaborator_blank_email_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepackage',
            name='build_started_at',
            field=models.DateTimeField(blank=True, help_text="When the current build attempt was queued, refreshed when a worker actually picks it up. A build has no other heartbeat, so this is what lets an attempt abandoned by a dead worker (or never dispatched at all) be reclaimed instead of pinning the package in 'building' forever.", null=True, verbose_name='Build Started At'),
        ),
    ]
