# Generated by Django 6.0.4 on 2026-08-25 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0044_score_package_build_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How long the session runs. Stored as a length rather than a closing instant so it survives a move of the start and a DST boundary; null means nobody has timed it and no surface may state an end.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Duration (minutes)'),
        ),
    ]
