# Generated by Django 6.0.4 on 2026-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0045_rehearsal_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_section_leader',
            field=models.BooleanField(default=False, help_text='Leads their voice section in this project. Listed first within it.', verbose_name='Section Leader'),
        ),
    ]
