# Generated by Django 6.0.4 on 2026-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0046_participation_section_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepackage',
            name='include_markings',
            field=models.BooleanField(default=False, help_text="Print the conductor's 'shared' markings onto the music pages. Only that layer: it is his message to the whole choir. A reader's own 'personal' pencil marks are never baked in here — they are composed per download, and nobody may switch on marks they are not allowed to see.", verbose_name="Include Conductor's Markings"),
        ),
        migrations.AddField(
            model_name='scorepackage',
            name='page_map',
            field=models.JSONField(blank=True, default=list, help_text='What each page of the stored book physically is: one row per page, in order, carrying its kind, printed folio, the program item / edition / source page it came from, and — for music — the box the source page was placed into, in A4 points. The binder trims, scales and re-centres every source page, so this is the ONLY record of where a given spot on an edition ended up in the book; without it nothing can be drawn onto the finished PDF at a musically correct position. Written by the generator only, and cleared whenever the file it describes is replaced or removed.', verbose_name='Page Map'),
        ),
    ]
