# Generated by Django 6.0.4 on 2026-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0047_scorepackage_include_markings_scorepackage_page_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='section_rank',
            field=models.PositiveIntegerField(blank=True, help_text="Position within this project's voice section. Blank = this section has not been arranged.", null=True, verbose_name='Order in Section'),
        ),
    ]
