# Generated by Django 6.0.4 on 2026-09-12 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0048_participation_section_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalDelegate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_see_leader_marks', models.BooleanField(default=True, help_text="Read access to the 'leader' annotation layer on this project's music. Never the conductor's private layer.", verbose_name='Sees Leader Markings')),
                ('can_take_roll_call', models.BooleanField(default=True, help_text="May record attendance for this project's rehearsals, including other singers' rows.", verbose_name='Takes Roll Call')),
                ('can_open_materials', models.BooleanField(default=True, help_text="Reaches this project's scores and programme even without a seat in its cast.", verbose_name='Opens Materials')),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this moment the delegation opens nothing. Blank = until the project closes.', null=True, verbose_name='Expires At')),
                ('note', models.CharField(blank=True, help_text='Why this delegation exists, for whoever reads the list later.', max_length=200, verbose_name='Note')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_delegations', to='roster.artist', verbose_name='Standing In')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_delegates', to='roster.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Rehearsal Delegate',
                'verbose_name_plural': 'Rehearsal Delegates',
                'indexes': [models.Index(fields=['artist', 'project'], name='roster_rehe_artist__5380c5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'artist'), name='unique_active_rehearsal_delegate')],
            },
        ),
    ]
