# Generated by Django 6.0.4 on 2026-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0049_rehearsaldelegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instrument',
            field=models.CharField(blank=True, help_text='Instrument played. Required for an instrumentalist, empty for everyone else.', max_length=60, verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='calls_instrumentalists',
            field=models.BooleanField(default=False, help_text="Whether a whole-cast rehearsal also calls the project's instrumentalists. Ignored when specific participants are invited.", verbose_name='Calls Instrumentalists'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='voice_type',
            field=models.CharField(choices=[('SOP', 'Soprano'), ('MEZ', 'Mezzo-Soprano'), ('ALT', 'Alto'), ('CT', 'Countertenor'), ('TEN', 'Tenor'), ('BAR', 'Baritone'), ('BAS', 'Bass'), ('DIR', 'Conductor'), ('INS', 'Instrumentalist')], max_length=5, verbose_name='Voice Type'),
        ),
    ]
