# Generated by Django 6.0.4 on 2026-09-19 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0050_artist_instrument_rehearsal_calls_instrumentalists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsaldelegate',
            options={'verbose_name': 'Project Leader', 'verbose_name_plural': 'Project Leaders'},
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_delegations', to='roster.artist', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='After this moment the leadership opens nothing. Blank = until the project closes.', null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Appointed By'),
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='note',
            field=models.CharField(blank=True, help_text='Why this person leads the project, for whoever reads the list later.', max_length=200, verbose_name='Note'),
        ),
    ]
