# Generated by Django 6.0.4 on 2026-09-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0051_alter_rehearsaldelegate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='led_by',
            field=models.ForeignKey(blank=True, help_text="Who runs this rehearsal. Blank = the project's conductor. Names a person; the powers come from the project's leader grant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_rehearsals', to='roster.artist', verbose_name='Led By'),
        ),
    ]
