# Generated by Django 6.0.4 on 2026-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0052_rehearsal_led_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsaldelegate',
            name='can_mark_for_choir',
            field=models.BooleanField(default=False, help_text="Writes the 'shared' annotation layer on this project's music — the choir's official markings, which every singer sees. Off unless the conductor lends his voice on purpose.", verbose_name='Marks for the Choir'),
        ),
    ]
