# Generated by Django 6.0.4 on 2026-09-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0053_rehearsaldelegate_can_mark_for_choir'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='debrief',
            field=models.TextField(blank=True, verbose_name='Debrief'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='debrief_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Debrief At'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='debrief_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roster.artist', verbose_name='Debrief By'),
        ),
    ]
