# Generated by Django 6.0.4 on 2026-09-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0054_rehearsal_debrief_rehearsal_debrief_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='default_voice_line',
            field=models.CharField(blank=True, choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('MS', 'Mezzo-Soprano'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('CT', 'Countertenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('BAR', 'Baritone'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], help_text="Voice line this singer takes when a piece's casting is filled from the line-up. Blank = derived from their voice type.", max_length=5, verbose_name='Line-up Seat'),
        ),
        migrations.AlterField(
            model_name='projectpiececasting',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('MS', 'Mezzo-Soprano'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('CT', 'Countertenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('BAR', 'Baritone'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=5, verbose_name='Voice Line (Divisi)'),
        ),
    ]
