# Generated by Django 6.0.4 on 2026-09-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0055_alter_participation_default_voice_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsaldelegate',
            options={'verbose_name': 'Assistant Conductor', 'verbose_name_plural': 'Assistant Conductors'},
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_delegations', to='roster.artist', verbose_name='Assistant Conductor'),
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='can_see_leader_marks',
            field=models.BooleanField(default=True, help_text="Read access to the 'leader' annotation layer on this project's music. Never the conductor's private layer.", verbose_name='Sees Markings for the Lead'),
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='After this moment the appointment opens nothing. Blank = until the project closes.', null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='rehearsaldelegate',
            name='note',
            field=models.CharField(blank=True, help_text='Why this person assists on the project, for whoever reads the list later.', max_length=200, verbose_name='Note'),
        ),
    ]
