# Generated by Django 6.0.4 on 2026-09-21 19:45

import roster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0056_alter_rehearsaldelegate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='called_sections',
            field=models.CharField(blank=True, help_text='Sections this rehearsal calls, as SATB letters. Blank = the whole cast. Ignored when specific participants are invited.', max_length=4, validators=[roster.models.validate_called_sections], verbose_name='Called Sections'),
        ),
    ]
