# Generated by Django 6.0.4 on 2026-09-21 20:43

import django.db.models.deletion
import roster.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0029_alter_piecevoicerequirement_voice_line_and_more'),
        ('roster', '0057_rehearsal_called_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='plan_announced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Plan Announced At'),
        ),
        migrations.CreateModel(
            name='RehearsalPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Label')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('starts_at', models.TimeField(blank=True, null=True, verbose_name='Starts At')),
                ('excluded_voice_lines', models.JSONField(blank=True, default=list, validators=[roster.models.validate_excluded_voice_lines], verbose_name='Excluded Voice Lines')),
                ('excludes_instrumentalists', models.BooleanField(default=False, verbose_name='Excludes Instrumentalists')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Done At')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rehearsal_plan_items', to='archive.piece', verbose_name='Piece')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='roster.rehearsal', verbose_name='Rehearsal')),
            ],
            options={
                'verbose_name': 'Rehearsal Plan Item',
                'verbose_name_plural': 'Rehearsal Plan Items',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('rehearsal', 'position'), name='unique_rehearsal_plan_position')],
            },
        ),
    ]
