# Generated by Django 6.0.4 on 2026-09-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0031_alter_track_options_and_more'),
        ('roster', '0059_alter_participation_default_voice_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='plan_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Plan Changed At'),
        ),
        migrations.AddField(
            model_name='rehearsalplanitem',
            name='is_break',
            field=models.BooleanField(default=False, verbose_name='Break'),
        ),
        migrations.AddField(
            model_name='rehearsalplanitem',
            name='is_reserve',
            field=models.BooleanField(default=False, verbose_name='Reserve'),
        ),
        migrations.AddField(
            model_name='rehearsalplanitem',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Skipped At'),
        ),
        migrations.AddConstraint(
            model_name='rehearsalplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('done_at__isnull', True), ('skipped_at__isnull', True), _connector='OR'), name='rehearsal_plan_one_verdict'),
        ),
        migrations.AddConstraint(
            model_name='rehearsalplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('is_break', False), ('piece__isnull', True), _connector='OR'), name='rehearsal_plan_break_names_no_piece'),
        ),
    ]
