# Generated by Django 6.0.4 on 2026-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0060_rehearsal_plan_changed_at_rehearsalplanitem_is_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsalplanitem',
            name='minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minutes'),
        ),
    ]
