# Generated by Django 6.0.4 on 2026-09-23 17:09
"""
Drops the fee, the paid flag and the payment timestamp from `Participation` and
`CrewAssignment`: the finance ledger holds every fee now. It depends on
`finance/0002`, which copies those columns into the ledger, so no database can
lose them before the copy has run.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_copy_roster_fees'),
        ('roster', '0061_rehearsalplanitem_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewassignment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='crewassignment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='crewassignment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='paid_at',
        ),
    ]
