# Generated by Django 6.0.4 on 2026-09-24 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_scoreedition_stand_whole_page'),
        ('roster', '0062_drop_legacy_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSoloAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('score_reference', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('gives_pitch', models.BooleanField(default=False)),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solo_assignments', to='roster.participation')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='project_solo_assignments', to='archive.piece')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='solo_assignments', to='roster.project')),
                ('reference_edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archive.scoreedition')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['project', 'piece', 'position'], name='roster_proj_project_dd3304_idx')],
            },
        ),
    ]
