# Generated by Django 6.0.4 on 2026-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0064_artist_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='proposed_extreme_high',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Proposed Extreme (High)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='proposed_extreme_low',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Proposed Extreme (Low)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='proposed_tessitura_high',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Proposed Tessitura (High)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='proposed_tessitura_low',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Proposed Tessitura (Low)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='vocal_range_comment',
            field=models.TextField(blank=True, verbose_name='Vocal Range Comment'),
        ),
        migrations.AddField(
            model_name='artist',
            name='vocal_range_proposed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vocal Range Proposed At'),
        ),
    ]
