# Generated by Django 6.0.4 on 2026-09-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0065_artist_proposed_extreme_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='assessed_extreme_high',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Assessed Extreme (High)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='assessed_extreme_low',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Assessed Extreme (Low)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='assessed_tessitura_high',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Assessed Tessitura (High)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='assessed_tessitura_low',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Assessed Tessitura (Low)'),
        ),
    ]
