# Generated by Django 6.0.4 on 2026-09-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0067_artist_assessed_range_from_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='vocal_range_bottom',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='vocal_range_top',
        ),
    ]
