# Generated by Django 6.0.4 on 2026-09-28 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0068_remove_artist_vocal_range_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='joins_on_site',
            field=models.BooleanField(default=False, help_text='Skips the points of the plan marked for the travelling party.', verbose_name='Joins on Site'),
        ),
        migrations.AddField(
            model_name='project',
            name='soundcheck_day',
            field=models.SmallIntegerField(default=0, help_text='Days from concert day: -1 is the day before, 0 is concert day.', validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Sound check (day)'),
        ),
        migrations.AddField(
            model_name='project',
            name='warmup_day',
            field=models.SmallIntegerField(default=0, help_text='Days from concert day: -1 is the day before, 0 is concert day.', validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Warm-up (day)'),
        ),
    ]
