# Generated by Django 6.0.4 on 2026-09-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0069_trip_plan_days_joins_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsaldelegate',
            name='can_manage_led_rehearsals',
            field=models.BooleanField(default=False, help_text='Writes and sends the plan of every rehearsal of this project that they lead, and sees the programme to do so. Never creates or deletes a rehearsal.', verbose_name='Plans the Rehearsals They Lead'),
        ),
    ]
