# Generated by Django 6.0.4 on 2026-09-02 18:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopySegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(db_index=True, help_text='Stable dotted id, reversible in both directions: the extractor produces it and the apply script writes back through it.', max_length=200, validators=[django.core.validators.RegexValidator(message="A segment key is dotted and namespaced, e.g. 'concert.wcielenie.essence'.", regex='^[a-z][a-z0-9]*(?:\\.[A-Za-z0-9_-]+)+$')])),
                ('locale', models.CharField(choices=[('pl', 'Polish'), ('en', 'English'), ('fr', 'French')], db_index=True, help_text='Which column of the desk this value belongs to.', max_length=5)),
                ('kind', models.CharField(choices=[('TEXT', 'Plain text'), ('HTML', 'Inline markup')], default='TEXT', help_text='Decides the editor the desk offers and the sanitizer the API runs.', max_length=10)),
                ('value', models.TextField(blank=True, help_text='The text as the repository currently holds it.')),
                ('source_hash', models.CharField(blank=True, help_text='For a non-Polish segment: hash of the Polish that this PUBLISHED value renders, stamped when a proposal was applied. Blank means no provenance was ever recorded — which is not the same as up to date.', max_length=64)),
                ('scope', models.CharField(db_index=True, help_text='The page this segment sits on. Always `scope_from_key(key)`.', max_length=120)),
                ('scope_label', models.CharField(blank=True, help_text="Human name of the page, for the contents list (e.g. 'Kontemplacja Wcielenia').", max_length=200)),
                ('label', models.CharField(blank=True, help_text="Human name of the field itself, for the row (e.g. 'Program · 3 · nota').", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text="Reading order within the page. The desk renders the text in the site's own sequence, not as a table sorted by key.")),
            ],
            options={
                'verbose_name': 'Copy Segment',
                'verbose_name_plural': 'Copy Segments',
                'db_table': 'copydesk_segment',
                'ordering': ['scope', 'order', 'key', 'locale'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='copydesk_seg_isdel_idx'), models.Index(fields=['scope', 'locale', 'order'], name='copydesk_seg_scope_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('key', 'locale'), name='unique_active_segment_per_locale')],
            },
        ),
        migrations.CreateModel(
            name='CopyProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value', models.TextField(blank=True, help_text="The proposed text, as rebuilt by the sanitizer for the segment's kind.")),
                ('source_hash', models.CharField(blank=True, help_text='Hash of the Polish this proposal was written against. Blank on a Polish proposal — a source renders nothing and so goes stale against nothing.', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PROPOSED', help_text='Where this proposal stands. ACCEPTED and REJECTED are terminal.', max_length=10)),
                ('comment', models.TextField(blank=True, help_text="The editor's note to the reviewer about this one segment.")),
                ('notified_at', models.DateTimeField(blank=True, db_index=True, help_text='When this proposal was carried by a digest to the reviewers. NULL means it is still unannounced; cleared again whenever the value changes, because a revised proposal is news a second time.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the proposal reached a terminal status.', null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When `apply-copy` wrote this accepted value into the repository. Accepted-and-unapplied is the patch waiting to be committed.', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Who wrote it. SET_NULL so a GDPR purge of an account leaves the editorial record — and any accepted wording still live on the site — intact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_proposals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Who accepted or rejected it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_reviews', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(help_text='The field and locale this proposal is for.', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='copydesk.copysegment')),
            ],
            options={
                'verbose_name': 'Copy Proposal',
                'verbose_name_plural': 'Copy Proposals',
                'db_table': 'copydesk_proposal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='copydesk_prop_isdel_idx'), models.Index(fields=['status', 'notified_at'], name='copydesk_prop_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['DRAFT', 'PROPOSED'])), fields=('segment', 'author'), name='unique_open_proposal_per_author')],
            },
        ),
    ]
