# Generated by Django 6.0.4 on 2026-09-03 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copydesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyScopeVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope', models.CharField(db_index=True, help_text='The page reviewed. Always a `scope_from_key` value.', max_length=120)),
                ('seen_at', models.DateTimeField(help_text='When this reader last declared the page reviewed. Set explicitly rather than on arrival or departure — see the class docstring.')),
                ('user', models.ForeignKey(help_text='Whose reading this records. CASCADE: a watermark outlives nobody.', on_delete=django.db.models.deletion.CASCADE, related_name='copy_scope_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copy Scope Visit',
                'verbose_name_plural': 'Copy Scope Visits',
                'db_table': 'copydesk_scope_visit',
                'ordering': ['scope'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='copydesk_visit_isdel_idx'), models.Index(fields=['user', 'scope'], name='copydesk_visit_user_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'scope'), name='unique_scope_visit_per_user')],
            },
        ),
    ]
