/**
 * @file downloadFile.js
 * @description Utility function for securely downloading binary files (PDF/ZIP/Audio).
 * Fetches the blob using the authorized JWT API instance and triggers 
 * the browser's native save dialog.
 * @author Krystian Bugalski
 */

import api from './api';

/**
 * Downloads a file from a secure API endpoint.
 * @param {string} url - The target API endpoint (e.g., '/api/participations/1/contract/')
 * @param {string} defaultFilename - Fallback filename if the backend doesn't provide one
 */
export const downloadFile = async (url, defaultFilename) => {
  try {
    const response = await api.get(url, { responseType: 'blob' });
    
    const disposition = response.headers['content-disposition'];
    let finalFilename = defaultFilename;
    
    // Extract the original filename generated by Django (if present in headers)
    if (disposition && disposition.includes('filename=')) {
      const match = disposition.match(/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/);
      if (match != null && match[1]) {
        finalFilename = match[1].replace(/['"]/g, '');
      }
    }
    
    // Create an invisible anchor tag to force the browser download dialog
    const downloadUrl = window.URL.createObjectURL(new Blob([response.data]));
    const anchor = document.createElement('a');
    anchor.style.display = 'none';
    anchor.href = downloadUrl;
    anchor.download = finalFilename;
    document.body.appendChild(anchor);
    anchor.click();
    
    // Garbage collection: clean up RAM and DOM
    window.URL.revokeObjectURL(downloadUrl);
    document.body.removeChild(anchor);
  } catch (error) {
    console.error("File download error:", error);
    throw new Error('Błąd podczas pobierania pliku. Sprawdź połączenie z serwerem.');
  }
};