# Generated by Django 6.0.4 on 2026-06-04 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0020_project_score_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.CharField(help_text='Short headline summarizing the conversation.', max_length=160)),
                ('context_type', models.CharField(choices=[('GENERAL', 'General'), ('PROJECT', 'Project')], default='GENERAL', help_text='Optional domain anchor (e.g. a specific project).', max_length=20)),
                ('context_id', models.UUIDField(blank=True, help_text='Loose reference to the anchored object (e.g. project_id). No hard FK by design.', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('ARCHIVED', 'Archived')], db_index=True, default='OPEN', help_text='Triage state of the conversation.', max_length=20)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Denormalized timestamp of the latest message for inbox sorting.')),
                ('artist', models.ForeignKey(help_text='The single non-management party of the conversation.', on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='roster.artist')),
                ('assignee', models.ForeignKey(blank=True, help_text='Manager the thread is directed to / who claimed it. Routing hint only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'db_table': 'messaging_thread',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(help_text='Message content. Length is validated at the DTO boundary.')),
                ('sender', models.ForeignKey(help_text='Author. SET_NULL preserves the message if the account is purged (GDPR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='Owning conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.thread')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messaging_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(help_text='Timestamp up to which the viewer has read this thread.')),
                ('thread', models.ForeignKey(help_text='Conversation this pointer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='messaging.thread')),
                ('user', models.ForeignKey(help_text='Viewer the pointer tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thread Read State',
                'verbose_name_plural': 'Thread Read States',
                'db_table': 'messaging_thread_read_state',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['artist', '-last_message_at'], name='messaging_t_artist__82b6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['assignee', 'status'], name='messaging_t_assigne_63d8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='messaging_m_thread__1731c3_idx'),
        ),
        migrations.AddIndex(
            model_name='threadreadstate',
            index=models.Index(fields=['user', 'thread'], name='messaging_t_user_id_1f1979_idx'),
        ),
        migrations.AddConstraint(
            model_name='threadreadstate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('thread', 'user'), name='unique_active_thread_read_state'),
        ),
    ]
