# Generated by Django 6.0.4 on 2026-06-04 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('roster', '0020_project_score_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the latest message; null until the first message. Drives sorting + unread.', null=True)),
                ('project', models.OneToOneField(help_text='The project this channel belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='roster.project')),
            ],
            options={
                'verbose_name': 'Project Channel',
                'verbose_name_plural': 'Project Channels',
                'db_table': 'messaging_project_channel',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(help_text='Message content.')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Pinned announcements surface at the top of the channel.')),
                ('sender', models.ForeignKey(help_text='Author. SET_NULL preserves the message if the account is purged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_channel_messages', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(help_text='Owning channel.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.projectchannel')),
            ],
            options={
                'verbose_name': 'Channel Message',
                'verbose_name_plural': 'Channel Messages',
                'db_table': 'messaging_channel_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='messaging_c_channel_edad7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('MANAGER', 'Manager')], default='MEMBER', help_text='MEMBER (synced from participation) or MANAGER.', max_length=20)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Timestamp up to which this member has read the channel.', null=True)),
                ('push_enabled', models.BooleanField(default=False, help_text='Per-channel opt-in for push notifications (off by default to avoid noise).')),
                ('user', models.ForeignKey(help_text='The member.', on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(help_text='The channel this membership grants access to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.projectchannel')),
            ],
            options={
                'verbose_name': 'Channel Membership',
                'verbose_name_plural': 'Channel Memberships',
                'db_table': 'messaging_channel_membership',
                'indexes': [models.Index(fields=['user', 'channel'], name='messaging_c_user_id_b95afb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('channel', 'user'), name='unique_active_channel_membership')],
            },
        ),
    ]
