# Generated by Django 6.0.4 on 2026-07-24 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_projectchannel_channelmessage_channelmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Owning manager. Gates visibility: null = shared intake queue; set = private to this manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
