# Generated by Django 6.0.4 on 2026-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_channelmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('MANAGER', 'Manager'), ('LEADER', 'Assistant Conductor')], default='MEMBER', help_text='MEMBER (synced from participation), LEADER (synced from project leadership) or MANAGER.', max_length=20),
        ),
    ]
