/**
 * @file content.config.ts
 * @description Content collections for the public site — concert "stations" and the
 *  seven-century repertoire catalog as typed DATA (Zod-validated), not hard-coded markup.
 *  The team edits two YAML files (src/content/*.yaml); KoncertyPage renders from them.
 *  Image fields hold bare photo() names (no extension) resolved at build via src/assets.
 * @architecture Astro islands 2026
 * @module content.config
 */
import { defineCollection } from "astro:content";
import { file } from "astro/loaders";
import { z } from "astro/zod";

/** Localized milestone editorial (per non-default locale) inside a concert's `about` block —
    every field optional so a partial translation still validates and falls back to Polish. */
const milestoneI18n = z
  .object({
    place: z.string().optional(),
    blurb: z.string().optional(),
    title: z.string().optional(),
  })
  .optional();

const concerts = defineCollection({
  loader: file("src/content/concerts.yaml"),
  schema: z.object({
    order: z.number(),
    roman: z.string(),
    latin: z.string(),
    title: z.string(),
    /** Presentational one-line venue + date, e.g. "Bazylika NSPJ, Kraków · 20 stycznia 2024". */
    meta: z.string(),
    /** Venue name alone — feeds schema.org Place.name (meta is display-only). */
    venue: z.string().optional(),
    /** ISO date (YYYY-MM-DD) for schema.org startDate. Omitted when the date is vague
        (a season or bare year); JSON-LD then skips startDate rather than fabricate one. */
    date: z.string().optional(),
    /** Concert hour "HH:MM" for a single-date concert — shown after `meta` in the detail
        hero and folded into the JSON-LD startDate. Tour entries carry time per-date. */
    time: z.string().optional(),
    /** Street address of the venue (e.g. "ul. Kopernika 26, Kraków") — JSON-LD Place.address
        only; the visible page keeps the quieter `meta`/`venue` register. */
    address: z.string().optional(),
    /** Short via-rail date label (e.g. "sty 2024"). The via-rail fill % is computed
        from order in the page, not stored here. */
    viaDate: z.string(),
    /** /o-nas milestone editorial — the About page derives its "Via" list from this
        collection (single source of truth with /koncerty). All fields optional:
        place falls back to `venue`, blurb to `essence`; a missing img renders the
        milestone row text-only. */
    about: z
      .object({
        /** Short display place for the milestone row, e.g. "Kraków · Łódź". */
        place: z.string().optional(),
        /** One-sentence o-nas note (shorter register than `essence`). */
        blurb: z.string().optional(),
        /** photo() base name for the 3:2 milestone image. */
        img: z.string().optional(),
        /** Localized milestone editorial (English) for the About page — place / blurb / a
            translated concert title. Each field falls back to its Polish counterpart (title to
            the concert `title`), so a partly-filled block still renders. Populate per concert as
            the site is translated; the full concert programme stays Polish-only for now. */
        en: milestoneI18n,
        /** Localized milestone editorial (French) — same fallbacks as `en`. */
        fr: milestoneI18n,
      })
      .optional(),
    accent: z.string(),
    essence: z.string(),
    facts: z.array(z.string()).default([]),
    variant: z.enum(["default", "memoriam", "liturgy"]).default("default"),
    reverse: z.boolean().default(false),
    /** Pre-blurred station-card wash — photo() base name, generated by blur-stations.cjs and
        served raw (~4 kB) as a CSS background on /koncerty. Blurred to nothing, so it never
        needs responsive variants. */
    bg: z.string(),
    /** The station's photograph, used full-bleed on the detail-page hero — photo() base name,
        resolved through bleedPair (so an art-directed `-mobile` crop can be added later).
        Names the SAME canonical file as `about.img` where the milestone and the hero share a
        frame: one file, one emit, no duplicate original in dist. Falls back to `<bg>-desktop`
        for stations that have no separate canonical original (the liturgy plate). */
    heroImg: z.string().optional(),
    /** Framed poster — photo() base name. Absent for the liturgy plate. */
    poster: z.string().optional(),
    posterAlt: z.string().optional(),
    realizacja: z.string().optional(),
    spotify: z.string().url().optional(),
    links: z.array(z.object({ label: z.string(), href: z.string().url() })).default([]),
    /** When true, /koncerty/[id] generates a dedicated page for this entry. */
    hasPage: z.boolean().default(false),
    /** The founder's own name for the programme, shown on the detail page instead of a
        bare work count (e.g. "Dziesięć spojrzeń — i bis"). Falls back to the label alone. */
    programLede: z.string().optional(),
    /** The dramaturgy of the evening — why THIS order. A short unsigned editorial lede that
        opens the programme ("kolejność jest częścią kompozycji"), grounded in the sequence
        itself, never in an invented quote. Rendered above the work list. */
    programArc: z.string().optional(),
    /** A quiet factual footnote for the WHOLE programme, rendered in the programme foot beside
        the standing texts/translations note. For what the work-list itself cannot carry — e.g.
        a touring concert whose instrumental interludes differed between evenings, so the list
        shows the ogniwa common to both. Facts only; the editorial voice belongs to programArc. */
    programNote: z.string().optional(),
    /** Overrides the standing provenance line under the programme ("Teksty łacińskie i
        oryginalne — z programów zespołu; przekłady polskie własne"). Set it whenever that
        sentence would not be true of THIS page — e.g. 9 Kart, whose Polish comes from the
        concert programme (the psalter the ensemble actually sang), not from us. Provenance is
        a claim like any other: it has to be right per page, so state less rather than guess. */
    textNote: z.string().optional(),
    /** The threshold of the evening — a short scene-setting beat rendered as a dark band right
        after the hero (place, hour, the rite of entry). Draws the reader across the doorway into
        the experience before the reflection. Grounded, never staged detail we can't attest. */
    prologue: z.string().optional(),
    /** Movements of the programme — the salvation-history acts the work-list is grouped into.
        Each program item names its movement `id`; the page emits an act header (Latin · Polish
        + one guiding line) whenever the movement changes. Empty ⇒ a flat list (back-compatible). */
    movements: z
      .array(
        z.object({
          id: z.string(),
          lat: z.string(),
          pl: z.string(),
          line: z.string().optional(),
          /** A full-bleed dark scripture beat rendered BEFORE this act — the night nave
              returning mid-reading at a dramatic hinge. Use sparingly (earned pivots only). */
          interlude: z
            .object({ lat: z.string(), pl: z.string().optional(), ref: z.string().optional() })
            .optional(),
        }),
      )
      .default([]),
    /** Self-hosted concert film (selected fragments), rendered in the shared custom player.
        `asset` is resolved through `lib/videos.ts`; `poster` is a photo() base name
        (falls back to the hero bg). `portrait` switches the player to the height-driven 9:16
        frame for phone-shot audience documents (their caption + note hang as a plaque beside
        it); `note` is the honest provenance line — which work, whose recording. */
    video: z
      .object({
        asset: z.enum(["landing-modal", "landing-wolanie", "landing-aeternam"]),
        caption: z.string().optional(),
        note: z.string().optional(),
        poster: z.string().optional(),
        portrait: z.boolean().default(false),
      })
      .optional(),
    /** Named "obsada" credits for the detail page — role → person (conductor, the Jesuit
        who gives the opening word, light direction…). Rendered as a quiet colophon block. */
    credits: z.array(z.object({ role: z.string(), name: z.string() })).default([]),
    /** The voices of THIS evening — the singers as they stood that night, grouped by voice
        part. CONSENT SCOPE: names are cleared for concert pages ONLY — never reuse them on
        /o-nas, the landing or press materials. Line-ups are per-evening (guests, later
        departures), so never frame the list as the ensemble's fixed roster or "founders".
        `detail` glosses a group (e.g. which works the solo quartet joined); `note` is a
        quiet factual footnote for the whole block (e.g. the debut sung without fees). */
    roster: z
      .object({
        groups: z.array(
          z.object({
            voice: z.string(),
            names: z.array(z.string()),
            detail: z.string().optional(),
          }),
        ),
        note: z.string().optional(),
      })
      .optional(),
    /** Multi-city tour dates. When present the detail page shows a "Wykonania" itinerary and
        JSON-LD emits one MusicEvent per date; single-date concerts keep using `date`/`venue`. */
    dates: z
      .array(
        z.object({
          date: z.string(), // ISO YYYY-MM-DD
          venue: z.string(), // full venue + city
          time: z.string().optional(), // e.g. "20:00"
        }),
      )
      .default([]),
    /** Documentary photographs from the evening (detail page gallery). Each `img` is a bare
        photo() base name; missing files are skipped at build (photoOptional), so a slot can be
        declared before the image is uploaded. */
    gallery: z
      .array(z.object({ img: z.string(), alt: z.string().optional(), caption: z.string().optional() }))
      .default([]),
    /** Verbum — the spoken threshold word: the live introduction given before the music
        begins (rite 01 on /koncerty). Distinct from `reflection` (the conductor's own
        authored note): this is someone else's live voice, transcribed and lightly edited
        for readability — edits are subtractive/corrective only, never paraphrase, and the
        page discloses the editing in a micro note. `quote` is a verbatim excerpt for the
        prominent blockquote; `text` is the full transcript behind a native reveal,
        `\n\n`-separated into paragraphs; `bridge` is OUR unsigned hand-off line closing
        the section (editorial register, not the speaker's). CONSENT: speaker consent
        covers the concert page — do not lift quotes to the landing or /koncerty without
        asking again. A film of the word (if any) joins later as a player under the
        transcript once its asset lands in assets/videos. */
    verbum: z
      .object({
        speaker: z.string(),
        quote: z.string(),
        text: z.string(),
        bridge: z.string().optional(),
      })
      .optional(),
    /** Florent-authored single reflection paragraph (concert page). */
    reflection: z.string().optional(),
    /** Author attribution for the reflection paragraph. */
    reflectionAttribution: z.string().optional(),
    /** OUR editorial bridge paragraph — rendered UNSIGNED, beneath the signed `reflection`.
        Never place editorial prose under `reflectionAttribution` (see concert-pages spec §1). */
    reflectionNote: z.string().optional(),
    /** Latin epigraph that opens the concert page (typically a biblical source). */
    inscriptio: z.string().optional(),
    /** Polish translation of inscriptio. */
    inscriptioPl: z.string().optional(),
    /** Biblical / source reference for the inscription (e.g. "Iz 11,1"). */
    inscriptioRef: z.string().optional(),
    /** Optional in-page pull-quote (composer or director on a single work). */
    pullQuote: z
      .object({
        text: z.string(),
        attribution: z.string(),
        about: z.string().optional(),
      })
      .optional(),
    program: z
      .array(
        z.object({
          composer: z.string(),
          /** Composer life-dates as a single string, e.g. "1942–2019". */
          years: z.string().optional(),
          work: z.string(),
          /** Year of composition. */
          year: z.string().optional(),
          /** Movement `id` this work belongs to (see concert-level `movements`). Consecutive
              items sharing an id sit under one act header. */
          movement: z.string().optional(),
          /** Vocal scoring as printed in the score, e.g. "a 8", "a12: SAATBB + SAATBB". */
          voicing: z.string().optional(),
          /** Duration as printed, e.g. "10′". */
          duration: z.string().optional(),
          /** Source / curatorial note for the work — one or two sentences on where it comes
              from and why it sits here (drawn from the ensemble's own programme book, factual,
              never a fabricated quote). Rendered as a quiet programme-book gloss. */
          note: z.string().optional(),
          /** A rubric — what HAPPENED in the room while this work sounded, printed the way a
              missal prints its instructions: not what was sung, but what was done. Reserved for
              an action the ensemble's own run-sheet wrote against the work ("OTWARCIE OŁTARZA
              podczas utworu" — the Veit Stoss altarpiece opening under Elgar's Lux aeterna).
              It is a stage direction, so keep it short, past-tense and attestable: prose about
              the work belongs in `note`, and an action BETWEEN works is a `clasp`. */
          rubric: z.string().optional(),
          /** Sung text in the original language (Latin / German / English…), verbatim. Store
              as a YAML block scalar to preserve line breaks. */
          text: z.string().optional(),
          /** Polish translation of `text`. */
          textPl: z.string().optional(),
          /** A clasp/refrain label rendered as a slim hairline row AFTER this item — used for
              "9 Kart", where Miserere returns between the psalms (e.g. "Miserere — część II"). */
          clasp: z.string().optional(),
          /** The words the clasp actually sang, verbatim — for a clasp that is a performed
              fragment rather than a mere marker ("Przerwa" carries none). In 9 Kart each return
              of the Miserere brings the next two verses of Psalm 51, so the psalm runs across
              the whole programme exactly as the evening distributed it. Store as a block scalar. */
          claspText: z.string().optional(),
          /** Polish translation of `claspText`. */
          claspTextPl: z.string().optional(),
          /** Liturgical incipit / source verse in Latin (concert page only). */
          inscriptio: z.string().optional(),
          /** Polish translation of inscriptio. */
          inscriptioPl: z.string().optional(),
          inscriptioRef: z.string().optional(),
          bis: z.boolean().default(false),
        }),
      )
      .default([]),
  }),
});

const repertoire = defineCollection({
  loader: file("src/content/repertoire.yaml"),
  schema: z.object({
    order: z.number(),
    title: z.string(),
    span: z.string(),
    entries: z.array(
      z.object({
        composer: z.string(),
        years: z.string().optional(),
        works: z.array(z.object({ title: z.string(), year: z.string().optional() })),
      }),
    ),
  }),
});

export const collections = { concerts, repertoire };
