# Generated by Django 6.0.2 on 2026-03-13 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('birth_year', models.CharField(blank=True, help_text='np. 1885', max_length=50, null=True, verbose_name='Rok urodzenia')),
                ('death_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rok śmierci')),
            ],
            options={
                'verbose_name': 'Kompozytor',
                'verbose_name_plural': 'Kompozytorzy',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł utworu')),
                ('arranger', models.CharField(blank=True, max_length=150, null=True, verbose_name='Aranżer')),
                ('composition_year', models.CharField(blank=True, help_text='np. 1638 lub XVI w.', max_length=100, null=True, verbose_name='Czas powstania')),
                ('language', models.CharField(blank=True, help_text='np. Łacina, Angielski', max_length=50, null=True, verbose_name='Język')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Format: HH:MM:SS', null=True, verbose_name='Szacowany czas trwania')),
                ('voicing', models.CharField(blank=True, help_text='np. SSAATTBB', max_length=50, verbose_name='Obsada wokalna')),
                ('description', models.TextField(blank=True, verbose_name='Uwagi / Opis')),
                ('sheet_music', models.FileField(blank=True, null=True, upload_to='sheet_music/', verbose_name='Nuty (Plik PDF)')),
                ('lyrics_original', models.TextField(blank=True, help_text='Tekst w języku oryginału', null=True, verbose_name='Tekst utworu')),
                ('lyrics_translation', models.TextField(blank=True, help_text='Polskie tłumaczenie', null=True, verbose_name='Tłumaczenie')),
                ('reference_recording', models.URLField(blank=True, help_text='Link do YouTube/Spotify', null=True, verbose_name='Nagranie referencyjne')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='archive.composer', verbose_name='Kompozytor')),
            ],
            options={
                'verbose_name': 'Utwór',
                'verbose_name_plural': 'Utwory',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_part', models.CharField(choices=[('S1', 'Sopran 1'), ('S2', 'Sopran 2'), ('A1', 'Alt 1'), ('A2', 'Alt 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bas 1'), ('B2', 'Bas 2'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament'), ('PRON', 'Wymowa (Dykcja/Język)')], max_length=10, verbose_name='Linia melodyczna')),
                ('audio_file', models.FileField(upload_to='audio_tracks/', verbose_name='Plik Audio (MIDI/MP3)')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.piece', verbose_name='Utwór')),
            ],
            options={
                'verbose_name': 'Ścieżka dźwiękowa',
                'verbose_name_plural': 'Ścieżki dźwiękowe',
            },
        ),
    ]
