# Generated by Django 6.0.2 on 2026-03-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracks', to='archive.piece', verbose_name='Utwór'),
        ),
    ]
