# Generated by Django 6.0.2 on 2026-03-15 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_track_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceVoiceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('voice_line', models.CharField(choices=[('S1', 'Sopran 1'), ('S2', 'Sopran 2'), ('A1', 'Alt 1'), ('A2', 'Alt 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bas 1'), ('B2', 'Bas 2'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament'), ('PRON', 'Wymowa (Dykcja/Język)')], max_length=10, verbose_name='Głos / Linia')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Wymagana ilość śpiewaków')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_requirements', to='archive.piece', verbose_name='Utwór')),
            ],
            options={
                'verbose_name': 'Wymaganie głosowe',
                'verbose_name_plural': 'Wymagania głosowe',
                'unique_together': {('piece', 'voice_line')},
            },
        ),
    ]
