# Generated by Django 6.0.2 on 2026-03-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_piecevoicerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='epoch',
            field=models.CharField(blank=True, choices=[('MED', 'Średniowiecze'), ('REN', 'Renesans'), ('BAR', 'Barok'), ('CLA', 'Klasycyzm'), ('ROM', 'Romantyzm'), ('M20', 'XX wiek'), ('CON', 'Muzyka Współczesna'), ('POP', 'Muzyka Rozrywkowa'), ('FOLK', 'Folk / Ludowa'), ('OTH', 'Inne')], max_length=4, null=True, verbose_name='Epoka'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composition_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok powstania'),
        ),
    ]
