# Generated by Django 6.0.2 on 2026-03-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_piece_epoch_alter_piece_composition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecevoicerequirement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='piecevoicerequirement',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='piecevoicerequirement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Sopran 1'), ('S2', 'Sopran 2'), ('A1', 'Alt 1'), ('A2', 'Alt 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bas 1'), ('B2', 'Bas 2'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament'), ('PRON', 'Wymowa (Dykcja/Język)')], max_length=12, verbose_name='Głos / Linia'),
        ),
        migrations.AlterField(
            model_name='track',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.piece', verbose_name='Utwór'),
        ),
    ]
