# Generated by Django 6.0.2 on 2026-03-24 14:07

import archive.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_remove_piecevoicerequirement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='sheet_music',
            field=models.FileField(blank=True, null=True, upload_to='sheet_music/', validators=[django.core.validators.FileExtensionValidator(['pdf']), archive.models.validate_file_size], verbose_name='Nuty (Plik PDF)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='audio_tracks/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'midi']), archive.models.validate_file_size], verbose_name='Plik Audio (MIDI/MP3)'),
        ),
    ]
