# Generated by Django 6.0.2 on 2026-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_piece_sheet_music_alter_track_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='reference_recording_spotify',
            field=models.URLField(blank=True, help_text='Link do Spotify', null=True, verbose_name='Nagranie (Spotify)'),
        ),
        migrations.AddField(
            model_name='piece',
            name='reference_recording_youtube',
            field=models.URLField(blank=True, help_text='Link do YouTube', null=True, verbose_name='Nagranie (Youtube)'),
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Sopran 1'), ('S2', 'Sopran 2'), ('S3', 'Sopran 3'), ('A1', 'Alt 1'), ('A2', 'Alt 2'), ('A3', 'Alt 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bas 1'), ('B2', 'Bas 2'), ('B3', 'Bas 3'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament'), ('PRON', 'Wymowa (Dykcja/Język)')], max_length=12, verbose_name='Głos / Linia'),
        ),
        migrations.AlterField(
            model_name='track',
            name='voice_part',
            field=models.CharField(choices=[('S1', 'Sopran 1'), ('S2', 'Sopran 2'), ('S3', 'Sopran 3'), ('A1', 'Alt 1'), ('A2', 'Alt 2'), ('A3', 'Alt 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bas 1'), ('B2', 'Bas 2'), ('B3', 'Bas 3'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (Wszyscy)'), ('ACC', 'Akompaniament'), ('PRON', 'Wymowa (Dykcja/Język)')], max_length=10, verbose_name='Linia melodyczna'),
        ),
    ]
