# Generated by Django 6.0.2 on 2026-04-03 06:44

import archive.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_remove_piece_reference_recording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='birth_year',
            field=models.CharField(blank=True, default='', help_text='np. 1885', max_length=50, verbose_name='Rok urodzenia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composer',
            name='death_year',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rok śmierci'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Imię'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='arranger',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Aranżer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='epoch',
            field=models.CharField(blank=True, choices=[('MED', 'Średniowiecze'), ('REN', 'Renesans'), ('BAR', 'Barok'), ('CLA', 'Klasycyzm'), ('ROM', 'Romantyzm'), ('M20', 'XX wiek'), ('CON', 'Muzyka Współczesna'), ('POP', 'Muzyka Rozrywkowa'), ('FOLK', 'Folk / Ludowa'), ('OTH', 'Inne')], default='', max_length=4, verbose_name='Epoka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='language',
            field=models.CharField(blank=True, default='', help_text='np. Łacina, Angielski', max_length=50, verbose_name='Język'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='lyrics_original',
            field=models.TextField(blank=True, default='', help_text='Tekst w języku oryginału', verbose_name='Tekst utworu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='lyrics_translation',
            field=models.TextField(blank=True, default='', help_text='Polskie tłumaczenie', verbose_name='Tłumaczenie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='reference_recording_spotify',
            field=models.URLField(blank=True, default='', help_text='Link do Spotify', verbose_name='Nagranie (Spotify)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='reference_recording_youtube',
            field=models.URLField(blank=True, default='', help_text='Link do YouTube', verbose_name='Nagranie (Youtube)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='sheet_music',
            field=models.FileField(blank=True, default='', upload_to='sheet_music/', validators=[django.core.validators.FileExtensionValidator(['pdf']), archive.models.validate_file_size], verbose_name='Nuty (Plik PDF)'),
            preserve_default=False,
        ),
    ]
