# Generated by Django 6.0.2 on 2026-04-08 18:01

import archive.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_alter_composer_birth_year_alter_composer_death_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ['last_name'], 'verbose_name': 'Composer', 'verbose_name_plural': 'Composers'},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['title'], 'verbose_name': 'Piece', 'verbose_name_plural': 'Pieces'},
        ),
        migrations.AlterModelOptions(
            name='piecevoicerequirement',
            options={'verbose_name': 'Voice Requirement', 'verbose_name_plural': 'Voice Requirements'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Audio Track', 'verbose_name_plural': 'Audio Tracks'},
        ),
        migrations.AlterField(
            model_name='composer',
            name='birth_year',
            field=models.CharField(blank=True, help_text='e.g. 1885', max_length=50, verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='death_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Death Year'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='arranger',
            field=models.CharField(blank=True, max_length=150, verbose_name='Arranger'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='archive.composer', verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composition_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Composition'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notes / Description'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='epoch',
            field=models.CharField(blank=True, choices=[('MED', 'Medieval'), ('REN', 'Renaissance'), ('BAR', 'Baroque'), ('CLA', 'Classical'), ('ROM', 'Romantic'), ('M20', '20th Century'), ('CON', 'Contemporary'), ('POP', 'Popular Music'), ('FOLK', 'Folk / Traditional'), ('OTH', 'Other')], max_length=4, verbose_name='Epoch'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True, verbose_name='Estimated Duration'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='language',
            field=models.CharField(blank=True, help_text='e.g. Latin, English', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='lyrics_original',
            field=models.TextField(blank=True, help_text='Original language text', verbose_name='Lyrics (Original)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='lyrics_translation',
            field=models.TextField(blank=True, help_text='Translated text', verbose_name='Lyrics (Translation)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='reference_recording_spotify',
            field=models.URLField(blank=True, help_text='Spotify URL', verbose_name='Recording (Spotify)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='reference_recording_youtube',
            field=models.URLField(blank=True, help_text='YouTube URL', verbose_name='Recording (YouTube)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='sheet_music',
            field=models.FileField(blank=True, upload_to='sheet_music/', validators=[django.core.validators.FileExtensionValidator(['pdf']), archive.models.validate_file_size], verbose_name='Sheet Music (PDF)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='voicing',
            field=models.CharField(blank=True, help_text='e.g. SSAATTBB', max_length=50, verbose_name='Voicing'),
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_requirements', to='archive.piece', verbose_name='Piece'),
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Required Singers'),
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=12, verbose_name='Voice Line'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='audio_tracks/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'midi']), archive.models.validate_file_size], verbose_name='Audio File (MIDI/MP3)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.piece', verbose_name='Piece'),
        ),
        migrations.AlterField(
            model_name='track',
            name='voice_part',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=10, verbose_name='Melody Line'),
        ),
    ]
