# Generated by Django 6.0.2 on 2026-04-09 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_alter_composer_options_alter_piece_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='piecevoicerequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='piecevoicerequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecevoicerequirement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piecevoicerequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pieces', to='archive.composer', verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='voice_requirements', to='archive.piece', verbose_name='Piece'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracks', to='archive.piece', verbose_name='Piece'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['last_name', 'first_name'], name='archive_com_last_na_90afbe_idx'),
        ),
        migrations.AddIndex(
            model_name='piece',
            index=models.Index(fields=['title'], name='archive_pie_title_3fab6c_idx'),
        ),
        migrations.AddIndex(
            model_name='piece',
            index=models.Index(fields=['epoch'], name='archive_pie_epoch_7afd30_idx'),
        ),
        migrations.AddConstraint(
            model_name='piecevoicerequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('piece', 'voice_line'), name='unique_active_voice_requirement'),
        ),
    ]
