# Hand-written migration for the Score Package Compiler feature (Phase 0).
# Extends Composer + Piece with canonical-identity / ingestion-status fields,
# and adds 7 new tables: Movement, ScoreEdition, Translation, Recording,
# Annotation, ProgramNote, ProvenanceRecord.
#
# Generated to match: archive/models.py @ 2026-05.
# If you change models.py, regenerate via `make shell` + `python manage.py
# makemigrations archive` inside the container — do not edit this file by
# hand once it has been applied to any environment.

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import archive.models  # for validate_file_size


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_piecevoicerequirement_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('roster', '0020_project_score_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ------------------------------------------------------------------
        # Composer extensions
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='composer',
            name='mbid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='MusicBrainz ID'),
        ),
        migrations.AddField(
            model_name='composer',
            name='wikidata_qid',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Wikidata QID'),
        ),
        migrations.AddField(
            model_name='composer',
            name='nationality',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='composer',
            name='period',
            field=models.CharField(
                blank=True, max_length=4,
                choices=[
                    ('MED', 'Medieval'), ('REN', 'Renaissance'), ('BAR', 'Baroque'),
                    ('CLA', 'Classical'), ('ROM', 'Romantic'), ('M20', '20th Century'),
                    ('CON', 'Contemporary'), ('POP', 'Popular Music'),
                    ('FOLK', 'Folk / Traditional'), ('OTH', 'Other'),
                ],
                verbose_name='Period',
            ),
        ),
        migrations.AddField(
            model_name='composer',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='composer',
            name='portrait_url',
            field=models.URLField(blank=True, verbose_name='Portrait URL'),
        ),
        migrations.AddField(
            model_name='composer',
            name='portrait_license',
            field=models.CharField(blank=True, max_length=40, verbose_name='Portrait License'),
        ),
        migrations.AddField(
            model_name='composer',
            name='aliases',
            field=models.JSONField(blank=True, default=list, verbose_name='Aliases'),
        ),

        # ------------------------------------------------------------------
        # Piece extensions
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='piece',
            name='mbid_work',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='MusicBrainz Work ID'),
        ),
        migrations.AddField(
            model_name='piece',
            name='opus_catalog',
            field=models.CharField(
                blank=True, max_length=40,
                help_text='e.g. BWV 243, K. 626, Op. 110 No. 2',
                verbose_name='Opus / Catalog',
            ),
        ),
        migrations.AddField(
            model_name='piece',
            name='musical_key',
            field=models.CharField(
                blank=True, max_length=20,
                help_text='e.g. D major, F# minor',
                verbose_name='Key',
            ),
        ),
        migrations.AddField(
            model_name='piece',
            name='text_source',
            field=models.CharField(
                blank=True, max_length=200,
                help_text='e.g. Luke 1:46-55, Psalm 23',
                verbose_name='Text Source',
            ),
        ),
        migrations.AddField(
            model_name='piece',
            name='lyrics_ipa',
            field=models.TextField(
                blank=True,
                help_text='IPA pronunciation guide for the sung text',
                verbose_name='Lyrics (IPA)',
            ),
        ),
        migrations.AddField(
            model_name='piece',
            name='ingestion_status',
            field=models.CharField(
                db_index=True, default='PEND', max_length=4,
                choices=[
                    ('PEND', 'Pending'), ('EXTR', 'Extracting metadata'),
                    ('ENRI', 'Looking up external sources'),
                    ('GENR', 'Generating program note & translations'),
                    ('AWAI', 'Awaiting conductor review'),
                    ('RDY ', 'Ready'), ('FAIL', 'Failed'),
                ],
                verbose_name='Ingestion Status',
            ),
        ),

        # ------------------------------------------------------------------
        # Movement
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('tempo_marking', models.CharField(blank=True, max_length=80, verbose_name='Tempo Marking')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (s)')),
                ('voicing_override', models.CharField(blank=True, max_length=50, verbose_name='Voicing Override')),
                ('starts_on_page', models.PositiveIntegerField(
                    blank=True, null=True,
                    help_text='Page in the source PDF where this movement begins',
                    verbose_name='Starts On Page',
                )),
                ('piece', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='movements', to='archive.piece',
                    verbose_name='Piece',
                )),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
                'ordering': ['piece', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_mov_is_dele_idx'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('piece', 'order_index'),
                name='unique_active_movement_order_per_piece',
            ),
        ),

        # ------------------------------------------------------------------
        # ScoreEdition
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='ScoreEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(
                    upload_to='score_editions/',
                    validators=[
                        django.core.validators.FileExtensionValidator(['pdf']),
                        archive.models.validate_file_size,
                    ],
                    verbose_name='PDF File',
                )),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('publisher', models.CharField(blank=True, max_length=120, verbose_name='Publisher')),
                ('edition_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edition Year')),
                ('editor_name', models.CharField(blank=True, max_length=120, verbose_name='Editor')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Edition')),
                ('sha256', models.CharField(
                    db_index=True, max_length=64,
                    help_text='Hex SHA-256 of the uploaded PDF — used for dedup across uploads',
                    verbose_name='SHA-256',
                )),
                ('ingestion_status', models.CharField(
                    db_index=True, default='PEND', max_length=4,
                    choices=[
                        ('PEND', 'Pending'), ('EXTR', 'Extracting metadata'),
                        ('ENRI', 'Looking up external sources'),
                        ('GENR', 'Generating program note & translations'),
                        ('AWAI', 'Awaiting conductor review'),
                        ('RDY ', 'Ready'), ('FAIL', 'Failed'),
                    ],
                    verbose_name='Ingestion Status',
                )),
                ('ingestion_cost_cents', models.PositiveIntegerField(
                    default=0,
                    help_text='Cumulative AI cost spent ingesting this edition, in USD cents.',
                    verbose_name='Ingestion Cost (¢)',
                )),
                ('ingestion_error', models.TextField(blank=True, verbose_name='Ingestion Error')),
                ('piece', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='editions', to='archive.piece',
                    verbose_name='Piece',
                )),
                ('uploaded_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL,
                    verbose_name='Uploaded By',
                )),
            ],
            options={
                'verbose_name': 'Score Edition',
                'verbose_name_plural': 'Score Editions',
            },
        ),
        migrations.AddIndex(
            model_name='scoreedition',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_sco_is_dele_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreedition',
            index=models.Index(fields=['piece', 'ingestion_status'], name='archive_sco_piece_i_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoreedition',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_default', True), ('is_deleted', False)),
                fields=('piece',),
                name='one_default_edition_per_piece',
            ),
        ),

        # ------------------------------------------------------------------
        # Translation
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('target_language', models.CharField(
                    max_length=8,
                    help_text="ISO 639-1, e.g. 'en', 'pl', 'fr'",
                    verbose_name='Target Language',
                )),
                ('text', models.TextField(verbose_name='Translated Text')),
                ('is_singable', models.BooleanField(
                    default=False,
                    help_text='True if the translation preserves meter for singing; False if literal.',
                    verbose_name='Singable',
                )),
                ('movement', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='translations', to='archive.movement',
                    verbose_name='Movement',
                )),
                ('piece', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='translations', to='archive.piece',
                    verbose_name='Piece',
                )),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_tra_is_dele_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['piece', 'target_language'], name='archive_tra_piece_l_idx'),
        ),

        # ------------------------------------------------------------------
        # Recording
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(
                    max_length=3,
                    choices=[('SPF', 'Spotify'), ('YTB', 'YouTube'), ('APL', 'Apple Music'), ('OTH', 'Other')],
                    verbose_name='Source',
                )),
                ('external_id', models.CharField(db_index=True, max_length=100, verbose_name='External ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('performer', models.CharField(blank=True, max_length=200, verbose_name='Performer / Ensemble')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (s)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('piece', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='recordings', to='archive.piece',
                    verbose_name='Piece',
                )),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_rec_is_dele_idx'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('source', 'external_id'),
                name='unique_active_recording_per_source',
            ),
        ),

        # ------------------------------------------------------------------
        # Annotation
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('page_number', models.PositiveIntegerField(verbose_name='Page Number')),
                ('annotation_type', models.CharField(
                    max_length=2,
                    choices=[
                        ('HL', 'Highlight'), ('CM', 'Text Comment'),
                        ('FH', 'Freehand Pen'), ('ST', 'Stamp / Symbol'),
                    ],
                    verbose_name='Type',
                )),
                ('payload', models.JSONField(
                    help_text='Shape varies by annotation_type: highlights store rect arrays, '
                              'freehand stores SVG path data, comments store text + anchor coordinates.',
                    verbose_name='Payload',
                )),
                ('color', models.CharField(default='#FFD700FF', max_length=9, verbose_name='Color (RGBA Hex)')),
                ('layer_name', models.CharField(
                    default='conductor', max_length=80,
                    help_text="e.g. 'conductor', 'shared', 'rehearsal-2026-05-18'",
                    verbose_name='Layer Name',
                )),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL,
                    verbose_name='Created By',
                )),
                ('edition', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='annotations', to='archive.scoreedition',
                    verbose_name='Edition',
                )),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
            },
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_ann_is_dele_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['edition', 'page_number'], name='archive_ann_edition_p_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['edition', 'layer_name'], name='archive_ann_edition_l_idx'),
        ),

        # ------------------------------------------------------------------
        # ProgramNote
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='ProgramNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=8, verbose_name='Language')),
                ('target_tone', models.CharField(
                    default='accessible', max_length=40,
                    help_text="e.g. 'accessible', 'scholarly', 'devotional'",
                    verbose_name='Target Tone',
                )),
                ('word_count_target', models.PositiveIntegerField(default=250, verbose_name='Word Count Target')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by Conductor')),
                ('piece', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='program_notes', to='archive.piece',
                    verbose_name='Piece',
                )),
                ('project', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='program_notes', to='roster.project',
                    verbose_name='Project',
                )),
            ],
            options={
                'verbose_name': 'Program Note',
                'verbose_name_plural': 'Program Notes',
            },
        ),
        migrations.AddIndex(
            model_name='programnote',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_pro_is_dele_idx'),
        ),
        migrations.AddIndex(
            model_name='programnote',
            index=models.Index(fields=['piece', 'language'], name='archive_pro_piece_l_idx'),
        ),
        migrations.AddIndex(
            model_name='programnote',
            index=models.Index(fields=['project', 'language'], name='archive_pro_project_l_idx'),
        ),

        # ------------------------------------------------------------------
        # ProvenanceRecord (generic FK)
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('field_name', models.CharField(max_length=80, verbose_name='Field Name')),
                ('source', models.CharField(
                    max_length=3,
                    choices=[
                        ('MAN', 'Manual entry'),
                        ('AIH', 'AI — Haiku 4.5'), ('AIS', 'AI — Sonnet 4.6'), ('AIO', 'AI — Opus 4.7'),
                        ('MBZ', 'MusicBrainz'), ('WKD', 'Wikidata'),
                        ('SPF', 'Spotify Web API'), ('YTB', 'YouTube Data API'),
                        ('IMS', 'IMSLP'),
                    ],
                    verbose_name='Source',
                )),
                ('source_reference', models.CharField(
                    blank=True, max_length=200,
                    help_text='mbid, Wikidata QID, Spotify track ID, URL, etc.',
                    verbose_name='Source Reference',
                )),
                ('confidence', models.FloatField(default=1.0, verbose_name='Confidence')),
                ('prompt_version', models.CharField(blank=True, max_length=80, verbose_name='Prompt Version')),
                ('model_version', models.CharField(blank=True, max_length=80, verbose_name='Model Version')),
                ('retrieved_at', models.DateTimeField(auto_now_add=True, verbose_name='Retrieved At')),
                ('content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='contenttypes.contenttype',
                    verbose_name='Content Type',
                )),
            ],
            options={
                'verbose_name': 'Provenance Record',
                'verbose_name_plural': 'Provenance Records',
            },
        ),
        migrations.AddIndex(
            model_name='provenancerecord',
            index=models.Index(fields=['is_deleted', '-created_at'], name='archive_prov_is_dele_idx'),
        ),
        migrations.AddIndex(
            model_name='provenancerecord',
            index=models.Index(fields=['content_type', 'object_id', 'field_name'], name='archive_prov_ct_obj_f_idx'),
        ),
        migrations.AddIndex(
            model_name='provenancerecord',
            index=models.Index(fields=['source', 'retrieved_at'], name='archive_prov_source_r_idx'),
        ),
    ]
