# Generated by Django 6.0.2 on 2026-05-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_score_package_compiler'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='archive_ann_is_dele_idx',
        ),
        migrations.RemoveIndex(
            model_name='movement',
            name='archive_mov_is_dele_idx',
        ),
        migrations.RemoveIndex(
            model_name='programnote',
            name='archive_pro_is_dele_idx',
        ),
        migrations.RemoveIndex(
            model_name='provenancerecord',
            name='archive_prov_is_dele_idx',
        ),
        migrations.RemoveIndex(
            model_name='recording',
            name='archive_rec_is_dele_idx',
        ),
        migrations.RemoveIndex(
            model_name='scoreedition',
            name='archive_sco_is_dele_idx',
        ),
        migrations.RemoveIndex(
            model_name='translation',
            name='archive_tra_is_dele_idx',
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='archive_ann_edition_9c5944_idx',
            old_name='archive_ann_edition_p_idx',
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='archive_ann_edition_5681bf_idx',
            old_name='archive_ann_edition_l_idx',
        ),
        migrations.RenameIndex(
            model_name='programnote',
            new_name='archive_pro_piece_i_1accc0_idx',
            old_name='archive_pro_piece_l_idx',
        ),
        migrations.RenameIndex(
            model_name='programnote',
            new_name='archive_pro_project_06bbf1_idx',
            old_name='archive_pro_project_l_idx',
        ),
        migrations.RenameIndex(
            model_name='provenancerecord',
            new_name='archive_pro_content_09e81a_idx',
            old_name='archive_prov_ct_obj_f_idx',
        ),
        migrations.RenameIndex(
            model_name='provenancerecord',
            new_name='archive_pro_source_b369bb_idx',
            old_name='archive_prov_source_r_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreedition',
            new_name='archive_sco_piece_i_102b74_idx',
            old_name='archive_sco_piece_i_idx',
        ),
        migrations.RenameIndex(
            model_name='translation',
            new_name='archive_tra_piece_i_6b8553_idx',
            old_name='archive_tra_piece_l_idx',
        ),
    ]
