# Generated by Django 6.0.4 on 2026-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_drop_legacy_piece_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='lyrics_original',
            field=models.TextField(blank=True, help_text='Original sung text', verbose_name='Lyrics (Original)'),
        ),
    ]
