# Generated by Django 6.0.4 on 2026-06-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_ingestion_cost_lifetime_and_progress_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='payload',
            field=models.JSONField(help_text="Shape varies by annotation_type, validated + sanitized server-side: FH/HL store {paths:[[[x,y],...]], width} (normalized 0..1, width as a fraction of page width); CM stores {x, y, text, display:'pin'|'inline'}; ST stores {x, y, symbol}.", verbose_name='Payload'),
        ),
    ]
