# Generated by Django 6.0.4 on 2026-07-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_annotation_payload_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translator',
            field=models.CharField(blank=True, help_text='Credited translator, printed under the translation in concert materials.', max_length=120, verbose_name='Translator'),
        ),
    ]
