# Generated by Django 6.0.4 on 2026-07-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_translation_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreedition',
            name='ingestion_run_started_at',
            field=models.DateTimeField(blank=True, help_text='When the CURRENT ingestion run was dispatched. Reset on every (re)ingest — the live elapsed timer counts from here, not from created_at (which, on a re-ingest, can be days old).', null=True, verbose_name='Ingestion Run Started At'),
        ),
    ]
