# Generated by Django 6.0.4 on 2026-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_scoreedition_ingestion_run_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='layer_name',
            field=models.CharField(default='conductor', help_text="e.g. 'conductor', 'shared', 'personal' (the writer's private pencil marks), 'rehearsal-2026-05-18'", max_length=80, verbose_name='Layer Name'),
        ),
    ]
