# Generated by Django 6.0.4 on 2026-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_alter_annotation_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='starting_pitches',
            field=models.JSONField(blank=True, default=list, help_text="Ordered starting pitches the conductor gives before the piece, top voice first: [{'voice': 'S', 'note': 6, 'octave': 4}, ...]. 'note' is a chromatic index (0=C … 11=B/H). Validated and sanitized in PieceSerializer.", verbose_name='Starting Pitches'),
        ),
    ]
