# Generated by Django 6.0.4 on 2026-07-03 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_piece_starting_pitches'),
        ('roster', '0031_scorepackage_card_default_elements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreedition',
            name='copies_owned',
            field=models.PositiveIntegerField(blank=True, help_text="Number of physical copies the ensemble owns (LICENSED_COPIES). Powers the 'more singers than copies' warning in the score-book cockpit.", null=True, verbose_name='Copies Owned'),
        ),
        migrations.AddField(
            model_name='scoreedition',
            name='license_type',
            field=models.CharField(choices=[('PD', 'Public domain'), ('LC', 'Licensed — physical copies owned'), ('PDG', 'Publisher digital license'), ('UNK', 'Unclassified (treated as protected)')], db_index=True, default='UNK', help_text='Copyright status. Anything other than PUBLIC_DOMAIN — including the UNKNOWN default — is treated as protected: choristers get an in-app, watermarked copy only, and every access is logged.', max_length=3, verbose_name='License Type'),
        ),
        migrations.CreateModel(
            name='ScoreAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('build_version', models.PositiveIntegerField(blank=True, help_text='Score-book build the binder access served (null for a single edition).', null=True, verbose_name='Build Version')),
                ('copy_number', models.PositiveIntegerField(blank=True, help_text='Per-recipient copy sequence stamped in the watermark; null for a clean serve.', null=True, verbose_name='Copy Number')),
                ('was_watermarked', models.BooleanField(default=False, help_text='Whether the served PDF carried the personal watermark footer.', verbose_name='Watermarked')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='archive.scoreedition', verbose_name='Edition')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roster.project', verbose_name='Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Score Access Log',
                'verbose_name_plural': 'Score Access Logs',
                'indexes': [models.Index(fields=['edition', 'user'], name='archive_sco_edition_34a582_idx'), models.Index(fields=['project', 'build_version', 'user'], name='archive_sco_project_2c963d_idx'), models.Index(fields=['-created_at'], name='archive_sco_created_ca0154_idx')],
            },
        ),
    ]
