# Generated by Django 6.0.4 on 2026-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_scoreedition_copies_owned_scoreedition_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenancerecord',
            name='source',
            field=models.CharField(choices=[('MAN', 'Manual entry'), ('AIH', 'AI — Haiku'), ('AIS', 'AI — Sonnet'), ('AIO', 'AI — Opus'), ('MBZ', 'MusicBrainz'), ('WKD', 'Wikidata'), ('SPF', 'Spotify Web API'), ('YTB', 'YouTube Data API'), ('IMS', 'IMSLP')], max_length=3, verbose_name='Source'),
        ),
    ]
