# Generated by Django 6.0.4 on 2026-08-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_alter_provenancerecord_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='piecevoicerequirement',
            name='unique_active_voice_requirement',
        ),
        migrations.AddField(
            model_name='piecevoicerequirement',
            name='edition',
            field=models.ForeignKey(blank=True, help_text='Arrangement this divisi belongs to. Blank = the whole piece.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_requirements', to='archive.scoreedition', verbose_name='Score Edition'),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.CharField(blank=True, help_text="Practice note shown with the track, e.g. 'tempo 90, from bar 34'.", max_length=200, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(blank=True, help_text='Arrangement this track was recorded for. Blank = the whole piece.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.scoreedition', verbose_name='Score Edition'),
        ),
        migrations.AddField(
            model_name='track',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Name of the uploaded file, kept so a manager can tell at a glance whether the right take landed on the right voice. Storage renames collisions, so the served path is not proof of what was picked.', max_length=255, verbose_name='Original Filename'),
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=12, verbose_name='Voice Line'),
        ),
        migrations.AlterField(
            model_name='track',
            name='voice_part',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=10, verbose_name='Melody Line'),
        ),
        migrations.AddConstraint(
            model_name='piecevoicerequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('edition__isnull', True), ('is_deleted', False)), fields=('piece', 'voice_line'), name='unique_active_voice_requirement'),
        ),
        migrations.AddConstraint(
            model_name='piecevoicerequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('edition__isnull', False), ('is_deleted', False)), fields=('edition', 'voice_line'), name='unique_active_edition_voice_requirement'),
        ),
    ]
