# Generated by Django 6.0.4 on 2026-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_edition_scoped_divisi_and_track_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='color',
            field=models.CharField(default='#1F2933', max_length=9, verbose_name='Color (RGBA Hex)'),
        ),
    ]
