# Generated by Django 6.0.4 on 2026-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_alter_annotation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='layer_name',
            field=models.CharField(default='conductor', help_text="e.g. 'conductor', 'shared', 'leader' (cues for whoever runs the rehearsal), 'personal' (the writer's private pencil marks), 'rehearsal-2026-05-18'", max_length=80, verbose_name='Layer Name'),
        ),
    ]
