# Generated by Django 6.0.4 on 2026-09-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0028_alter_annotation_layer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('MS', 'Mezzo-Soprano'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('CT', 'Countertenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('BAR', 'Baritone'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=12, verbose_name='Voice Line'),
        ),
        migrations.AlterField(
            model_name='track',
            name='voice_part',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('MS', 'Mezzo-Soprano'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('CT', 'Countertenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('BAR', 'Baritone'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=10, verbose_name='Melody Line'),
        ),
    ]
