# Generated by Django 6.0.4 on 2026-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0029_alter_piecevoicerequirement_voice_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': [models.Case(models.When(then=models.Value(0), voice_part='S1'), models.When(then=models.Value(1), voice_part='S2'), models.When(then=models.Value(2), voice_part='S3'), models.When(then=models.Value(3), voice_part='MS'), models.When(then=models.Value(4), voice_part='A1'), models.When(then=models.Value(5), voice_part='A2'), models.When(then=models.Value(6), voice_part='A3'), models.When(then=models.Value(7), voice_part='CT'), models.When(then=models.Value(8), voice_part='T1'), models.When(then=models.Value(9), voice_part='T2'), models.When(then=models.Value(10), voice_part='T3'), models.When(then=models.Value(11), voice_part='BAR'), models.When(then=models.Value(12), voice_part='B1'), models.When(then=models.Value(13), voice_part='B2'), models.When(then=models.Value(14), voice_part='B3'), models.When(then=models.Value(15), voice_part='V1'), models.When(then=models.Value(16), voice_part='V2'), models.When(then=models.Value(17), voice_part='V3'), models.When(then=models.Value(18), voice_part='V4'), models.When(then=models.Value(19), voice_part='SOLO'), models.When(then=models.Value(20), voice_part='VP'), models.When(then=models.Value(21), voice_part='TUTTI'), models.When(then=models.Value(22), voice_part='BACK'), models.When(then=models.Value(23), voice_part='ACC'), models.When(then=models.Value(24), voice_part='PRON'), default=models.Value(25), output_field=models.IntegerField()), 'created_at'], 'verbose_name': 'Audio Track', 'verbose_name_plural': 'Audio Tracks'},
        ),
    ]
