# Generated by Django 6.0.4 on 2026-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0030_alter_track_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': [models.Case(models.When(then=models.Value(0), voice_part='S1'), models.When(then=models.Value(1), voice_part='S2'), models.When(then=models.Value(2), voice_part='S3'), models.When(then=models.Value(3), voice_part='MS'), models.When(then=models.Value(4), voice_part='A1'), models.When(then=models.Value(5), voice_part='A2'), models.When(then=models.Value(6), voice_part='A3'), models.When(then=models.Value(7), voice_part='CT'), models.When(then=models.Value(8), voice_part='T1'), models.When(then=models.Value(9), voice_part='T2'), models.When(then=models.Value(10), voice_part='T3'), models.When(then=models.Value(11), voice_part='BAR'), models.When(then=models.Value(12), voice_part='B1'), models.When(then=models.Value(13), voice_part='B2'), models.When(then=models.Value(14), voice_part='B3'), models.When(then=models.Value(15), voice_part='V1'), models.When(then=models.Value(16), voice_part='V2'), models.When(then=models.Value(17), voice_part='V3'), models.When(then=models.Value(18), voice_part='V4'), models.When(then=models.Value(19), voice_part='SOLO'), models.When(then=models.Value(20), voice_part='VP'), models.When(then=models.Value(21), voice_part='TUTTI'), models.When(then=models.Value(22), voice_part='BACK'), models.When(then=models.Value(23), voice_part='INSTR'), models.When(then=models.Value(24), voice_part='ACC'), models.When(then=models.Value(25), voice_part='PRON'), default=models.Value(26), output_field=models.IntegerField()), 'created_at'], 'verbose_name': 'Audio Track', 'verbose_name_plural': 'Audio Tracks'},
        ),
        migrations.AlterField(
            model_name='piecevoicerequirement',
            name='voice_line',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('MS', 'Mezzo-Soprano'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('CT', 'Countertenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('BAR', 'Baritone'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('INSTR', 'Instrumental'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=12, verbose_name='Voice Line'),
        ),
        migrations.AlterField(
            model_name='track',
            name='voice_part',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('S3', 'Soprano 3'), ('MS', 'Mezzo-Soprano'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('A3', 'Alto 3'), ('CT', 'Countertenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('T3', 'Tenor 3'), ('BAR', 'Baritone'), ('B1', 'Bass 1'), ('B2', 'Bass 2'), ('B3', 'Bass 3'), ('V1', 'Voice 1'), ('V2', 'Voice 2'), ('V3', 'Voice 3'), ('V4', 'Voice 4'), ('SOLO', 'Solo'), ('VP', 'Vocal Percussion / Beatbox'), ('TUTTI', 'Tutti (All)'), ('BACK', 'Backing Vocals'), ('INSTR', 'Instrumental'), ('ACC', 'Accompaniment'), ('PRON', 'Pronunciation / Diction')], max_length=10, verbose_name='Melody Line'),
        ),
    ]
