# Generated by Django 6.0.4 on 2026-09-23 08:02

import re

from django.db import migrations, models

# How the conductor marked the target-tempo takes before the field existed:
# the Tutti take's note (or its filename) was renamed to "Tempo giusto". The
# pattern also accepts the "tiempo gusto" spelling that turns up in practice.
TEMPO_GIUSTO_MARK = re.compile(r't[i]?empo\s*g[i]?usto', re.IGNORECASE)
# A note that says nothing but the mark becomes the label itself, so it is
# cleared rather than printed twice beside the take.
MARK_ONLY = re.compile(r'^\W*t[i]?empo\s*g[i]?usto\W*$', re.IGNORECASE)


def flag_marked_tempo_giusto_takes(apps, schema_editor):
    Track = apps.get_model('archive', 'Track')
    for track in Track.objects.filter(voice_part='TUTTI').order_by():
        if not (
            TEMPO_GIUSTO_MARK.search(track.description or '')
            or TEMPO_GIUSTO_MARK.search(track.original_filename or '')
        ):
            continue
        track.kind = 'TEMPO_GIUSTO'
        if MARK_ONLY.match(track.description or ''):
            track.description = ''
        track.save(update_fields=['kind', 'description'])


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0031_alter_track_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='kind',
            field=models.CharField(choices=[('PRACTICE', 'Practice'), ('TEMPO_GIUSTO', 'Tempo giusto')], default='PRACTICE', help_text='Practice takes play together in the mixer and must share one length; a tempo giusto take is the target-tempo recording, heard on its own.', max_length=16, verbose_name='Take'),
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': [models.Case(models.When(kind='TEMPO_GIUSTO', then=models.Value(1)), default=models.Value(0), output_field=models.IntegerField()), models.Case(models.When(then=models.Value(0), voice_part='S1'), models.When(then=models.Value(1), voice_part='S2'), models.When(then=models.Value(2), voice_part='S3'), models.When(then=models.Value(3), voice_part='MS'), models.When(then=models.Value(4), voice_part='A1'), models.When(then=models.Value(5), voice_part='A2'), models.When(then=models.Value(6), voice_part='A3'), models.When(then=models.Value(7), voice_part='CT'), models.When(then=models.Value(8), voice_part='T1'), models.When(then=models.Value(9), voice_part='T2'), models.When(then=models.Value(10), voice_part='T3'), models.When(then=models.Value(11), voice_part='BAR'), models.When(then=models.Value(12), voice_part='B1'), models.When(then=models.Value(13), voice_part='B2'), models.When(then=models.Value(14), voice_part='B3'), models.When(then=models.Value(15), voice_part='V1'), models.When(then=models.Value(16), voice_part='V2'), models.When(then=models.Value(17), voice_part='V3'), models.When(then=models.Value(18), voice_part='V4'), models.When(then=models.Value(19), voice_part='SOLO'), models.When(then=models.Value(20), voice_part='VP'), models.When(then=models.Value(21), voice_part='TUTTI'), models.When(then=models.Value(22), voice_part='BACK'), models.When(then=models.Value(23), voice_part='INSTR'), models.When(then=models.Value(24), voice_part='ACC'), models.When(then=models.Value(25), voice_part='PRON'), default=models.Value(26), output_field=models.IntegerField()), 'created_at'], 'verbose_name': 'Audio Track', 'verbose_name_plural': 'Audio Tracks'},
        ),
        migrations.RunPython(flag_marked_tempo_giusto_takes, migrations.RunPython.noop),
    ]
