# Generated by Django 6.0.4 on 2026-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0032_track_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreedition',
            name='stand_whole_page',
            field=models.BooleanField(default=False, help_text='The score sets one system per page, so a partial view on the stand would cut it. Opens every page whole in performance mode.', verbose_name='Whole pages on the stand'),
        ),
        migrations.AddField(
            model_name='scoreedition',
            name='stand_whole_page_suggested',
            field=models.BooleanField(blank=True, help_text='What the ingestion analysis read off the pages: whether any page of music carries a single system. A suggestion for the librarian, never applied by itself. Blank when the analysis did not answer.', null=True, verbose_name='Whole pages on the stand — suggested by analysis'),
        ),
    ]
