# Generated by Django 6.0.4 on 2026-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_scoreedition_stand_whole_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='lyrics_ipa_system',
            field=models.CharField(blank=True, choices=[('germanic', 'German (Central European)'), ('italianate', 'Italianate (Roman)'), ('classical', 'Classical (restored)')], help_text='Latin pronunciation the IPA guide is written in', max_length=12, verbose_name='IPA pronunciation system'),
        ),
    ]
