# Generated by Django 6.0.2 on 2026-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], help_text='Standard touring or uniform shirt size.', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_notes',
            field=models.TextField(blank=True, help_text='Specific allergies or custom dietary instructions.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'Brak wymagań'), ('vege', 'Wegetariańska'), ('vegan', 'Wegańska'), ('gf', 'Bez glutenu'), ('lf', 'Bez laktozy')], default='none', help_text='Primary dietary requirement for catering.', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Height in centimeters. Crucial for stage risers positioning.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shoe_size',
            field=models.CharField(blank=True, help_text='European shoe size format (e.g., 42, 42.5).', max_length=10),
        ),
    ]
