# Generated by Django 6.0.2 on 2026-04-08 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_clothing_size_userprofile_dietary_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret token for iCal feed subscription.', unique=True),
        ),
    ]
