# Generated by Django 6.0.2 on 2026-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Determines if the user receives non-critical operational emails.'),
        ),
    ]
