# Generated by Django 6.0.2 on 2026-04-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager / Conductor'), ('ARTIST', 'Artist / Singer'), ('CREW', 'Crew / Collaborator')], default='ARTIST', help_text='Business role defining application access level.', max_length=20),
        ),
    ]
