# Generated by Django 6.0.2 on 2026-04-10 10:52
from django.db import migrations
from core.constants import AppRole 

def set_initial_roles(apps, schema_editor):
    """
    Enterprise Data Migration: Initializes business roles for existing identities.
    Promotes Superusers to MANAGERS while maintaining the default ARTIST role for others.
    """
    UserProfile = apps.get_model('core', 'UserProfile')
    
    updated_count = UserProfile.objects.filter(
        user__is_superuser=True
    ).update(role=AppRole.MANAGER)
    
    print(f"\n[Migration] Successfully assigned MANAGER role to {updated_count} superuser(s).")

def reverse_roles(apps, schema_editor):
    """Fallback: Resets all roles to ARTIST if migration is rolled back."""
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.update(role=AppRole.ARTIST)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_role'), 
    ]

    operations = [
        migrations.RunPython(set_initial_roles, reverse_code=reverse_roles),
    ]