# Generated by Django 6.0.2 on 2026-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assign_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Local timezone for this entity. Critical for UI rendering and iCal feeds.', max_length=63),
        ),
    ]
