# Generated by Django 6.0.2 on 2026-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Europe/Warsaw', help_text='Local timezone for this entity. Critical for UI rendering and iCal feeds.', max_length=63),
        ),
    ]
