# Generated by Django 6.0.2 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('pl', 'Polish'), ('fr', 'French')],
                default='en',
                help_text='User preferred UI language.',
                max_length=10,
            ),
        ),
    ]
