# Generated by Django 6.0.4 on 2026-06-12 07:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Full-size (square, 512px) profile picture, re-encoded to WebP.', null=True, upload_to=core.models.avatar_upload_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_thumb',
            field=models.ImageField(blank=True, help_text='Small (96px) thumbnail derived from the avatar for dense lists.', null=True, upload_to=core.models.avatar_upload_path),
        ),
    ]
