# Generated by Django 6.0.4 on 2026-06-15 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_avatar_userprofile_avatar_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digest_enabled',
            field=models.BooleanField(default=True, help_text='Batch routine informational manager alerts into a single daily digest email.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=8, help_text="Local hour (0-23, in the user's timezone) the daily digest is delivered.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent digest dispatch. Guards against duplicates.', null=True),
        ),
    ]
