# Generated by Django 6.0.4 on 2026-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_digest_enabled_userprofile_digest_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_undeliverable',
            field=models.BooleanField(default=False, help_text='Set automatically on a hard bounce or spam complaint. Suppresses notification email.'),
        ),
    ]
