# Generated by Django 6.0.4 on 2026-06-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_language_default_and_backfill_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salutation',
            field=models.CharField(choices=[('F', 'Feminine'), ('M', 'Masculine'), ('N', 'Neutral / unspecified')], default='N', help_text='Grammatical form of address for greetings only (e.g. PL Drogi/Droga, FR Cher/Chère). Optional; NEUTRAL makes no assumption.', max_length=1),
        ),
    ]
