# Generated by Django 6.0.4 on 2026-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, help_text="When the user last opened the notification centre. Drives the 'new since seen' bell badge: opening clears the count without marking individual notifications as read.", null=True),
        ),
    ]
