# Generated by Django 6.0.4 on 2026-06-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_notifications_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='welcome_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the member first completed the one-time home-screen welcome. Stamped once, server-side, so the WelcomeMoment card greets a new member exactly once per account — on every device they sign in from, not once per browser.', null=True),
        ),
    ]
