# Generated by Django 6.0.4 on 2026-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_welcome_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text="Server-side timestamp of the user's acceptance of the Terms of Service and Privacy Policy at account activation. Legal evidence of consent — stamped once, never updated on later logins.", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_version',
            field=models.CharField(blank=True, default='', help_text="Version identifier (date-stamped, e.g. '2026-07-09') of the legal documents the user accepted at activation.", max_length=20),
        ),
    ]
