# Generated by Django 6.0.4 on 2026-07-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preference',
        ),
    ]
