# Generated by Django 6.0.4 on 2026-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_email_case_insensitive_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name_vocative',
            field=models.CharField(blank=True, help_text="Polish vocative form, e.g. 'Krystianie' for 'Krystian'. Used in greetings; blank falls back to the nominative first name. Lives here rather than on the choral profile because managers and crew are addressed too, and they have no Artist row.", max_length=150, verbose_name='First Name (Vocative)'),
        ),
    ]
