# Generated by Django 6.0.4 on 2026-08-15 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_identity_vocative_moves_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('BUG', 'Something is broken'), ('CONFUSING', 'Something is unclear'), ('IDEA', 'Suggestion'), ('PRAISE', 'Praise')], db_index=True, default='BUG', help_text="The reporter's own classification of what they are telling us.", max_length=12)),
                ('body', models.TextField(help_text='What the reporter wrote. Length is capped at the serializer boundary.')),
                ('route', models.CharField(blank=True, help_text='SPA path the reporter was on (e.g. /panel/projects/<id>/casting).', max_length=300)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Whitelisted client environment snapshot. Rebuilt key-by-key by the serializer — never stored as the client sent it.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='NEW', help_text='Triage state, advanced by hand.', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Internal triage note. Never shown to the reporter.')),
                ('reporter', models.ForeignKey(blank=True, help_text='Author. SET_NULL preserves the report if the account is purged (GDPR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'db_table': 'core_feedback_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='core_feedback_isdel_idx'), models.Index(fields=['status', '-created_at'], name='core_feedback_status_idx')],
            },
        ),
    ]
