# Generated by Django 6.0.4 on 2026-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_feedbackreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_email_offer_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the member answered the one-time offer to drop notification e-mail because push was proven to reach them. Stamped on either answer — the offer is a question asked once, not a reminder. Server-side for the same reason as welcome_seen_at: the choice is about the account, so declining on one device must settle it everywhere.', null=True),
        ),
    ]
