# Generated by Django 6.0.4 on 2026-09-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userprofile_push_email_offer_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_site_copy',
            field=models.BooleanField(default=False, help_text="Grants access to the copy desk (/redakcja) to propose changes to the public site's text. Set from the admin; independent of role."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='copy_desk_seen_at',
            field=models.DateTimeField(blank=True, help_text="When the editor last opened the copy desk. Drives the 'new since your last visit' flag, which is what keeps a later stage's new segments from reading as a fresh wall of text. Server-side for the same reason as welcome_seen_at: the visit is a fact about the person, not about a browser.", null=True),
        ),
    ]
