# Generated by Django 6.0.4 on 2026-09-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_can_edit_site_copy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='copy_desk_seen_at',
        ),
    ]
