# Generated by Django 6.0.4 on 2026-09-22 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_userprofile_copy_desk_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(help_text='Plain text, line breaks preserved. Length is capped at the serializer boundary.')),
                ('is_done', models.BooleanField(default=False, help_text='Toggled by the owner. Drives ordering (open notes first) and the 30-day retention sweep once set.')),
                ('done_at', models.DateTimeField(blank=True, help_text='Stamped when is_done is set, cleared when unset. Server-side only — the retention window is measured from here.', null=True)),
                ('owner', models.ForeignKey(help_text='The account this note belongs to. Never read by any other user, manager or superuser included.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'core_note',
                'ordering': ['is_done', '-created_at'],
                'indexes': [models.Index(fields=['is_deleted', '-created_at'], name='core_note_isdel_idx'), models.Index(fields=['owner', 'is_done', '-created_at'], name='core_note_owner_idx')],
            },
        ),
    ]
