# Generated by Django 6.0.4 on 2026-09-26 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='season_calendar_enabled',
            field=models.BooleanField(default=False, help_text='Serves the whole published season at the season calendar address. Honoured only while the account is an active manager.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='season_calendar_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Secret token for the season iCal feed. Empty until first enabled.', null=True),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('season_calendar_token',), name='unique_active_season_calendar_token'),
        ),
    ]
