# Generated by Django 6.0.4 on 2026-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userprofile_season_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pitch_notation',
            field=models.CharField(blank=True, choices=[('', 'Follow the language'), ('polish', 'Polish and German (a¹)'), ('international', 'International (A4)'), ('french', 'French (la3)')], default='', help_text='Notation this person reads pitch names in (vocal ranges and the like). Blank follows the UI language.', max_length=16),
        ),
    ]
