# Generated by Django 6.0.4 on 2026-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_pitch_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='digest_enabled',
            field=models.BooleanField(default=True, help_text='E-mail routine manager reports as one daily digest instead of one e-mail each. Push notifications are not affected.'),
        ),
    ]
